// Run only against an isolated fixture with log-only email and no AI key.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path'),{execFileSync}=require('node:child_process');
const base=process.env.STUDIODECK_TEST_URL,log=process.env.STUDIODECK_TEST_MAIL_LOG,terms=process.env.STUDIODECK_TEST_TERMS,container=process.env.STUDIODECK_TEST_CONTAINER;
if(!base||!log||!terms||!container)throw Error('Set STUDIODECK_TEST_URL, STUDIODECK_TEST_MAIL_LOG, STUDIODECK_TEST_TERMS and STUDIODECK_TEST_CONTAINER to an isolated fixture.');
const artifacts=fs.mkdtempSync('/tmp/studiodeck-pack-browser-');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:false,args:['--no-sandbox','--headless=new']});let page;
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.request.post(base+'/api.php?action=request_login',{data:{email:`pack-${Date.now()}@example.test`}});const token=fs.readFileSync(log,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await context.request.post(base+'/api.php?action=consume_login',{data:{token}});await page.goto(base+'/choose');await page.locator('[data-action=destination-studio]').first().click();await page.locator('#project-search').waitFor();
  const session=await (await context.request.get(base+'/api.php?action=session')).json();
  const api=async(action,data)=>{const r=data===undefined?await context.request.get(base+'/api.php?action='+action):await context.request.post(base+'/api.php?action='+action,{data,headers:{'X-CSRF-Token':session.csrf}});assert.ok(r.ok(),action+': '+await r.text());return r.json();};
  await page.locator('[data-action=settings]').click();await page.getByRole('button',{name:'Manage starting pack'}).click();await page.getByRole('button',{name:'Use example slides'}).click();await page.locator('.pack-item').nth(2).waitFor();assert.equal(await page.locator('.pack-item').count(),3);
  await page.getByRole('button',{name:'Add reference PDF'}).click();await page.locator('.modal [name=title]').fill('Studio terms & conditions');await page.locator('.modal [name=file]').setInputFiles(terms);await page.getByRole('button',{name:'Save template'}).click();await page.locator('.pack-item').nth(3).waitFor();await page.screenshot({path:path.join(artifacts,'library-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('button',{name:'Next: project details',exact:true}).click();await page.locator('.modal [name=name]').fill('Villa Starting Pack');await page.locator('.pack-wizard summary').click();const choices=page.locator('[name=pack_version]');assert.equal(await choices.count(),4);await page.locator('.pack-wizard .checkbox-label').filter({hasText:'Let’s talk'}).locator('input').uncheck();await page.getByRole('button',{name:'Next: upload files'}).click();await page.getByRole('button',{name:'Back',exact:true}).click();await page.locator('.pack-wizard summary').click();assert.equal(await page.locator('[name=pack_version]:checked').count(),3);await page.getByRole('button',{name:'Next: upload files'}).click();await page.getByRole('button',{name:'Add files later'}).click();await page.locator('.overview-grid').waitFor();
  const pid=new URL(page.url()).pathname.split('/').at(-1);let d=await api('project&id='+pid);const iid=d.iteration.id;assert.equal(d.files.length,1);
  execFileSync('docker',['exec',container,'php','/app/scripts/worker.php','--once']);await page.reload();assert.equal(await page.getByRole('button',{name:'Review pack',exact:true}).count(),0);assert.equal(await page.locator('#app .pack-summary').count(),0);
  await api('save_slide',{iteration:iid,slide_id:'intro',title:'A personal welcome',description:'Tailored to Villa Starting Pack'});
  await page.locator('[data-action=settings]').click();await page.getByRole('button',{name:'Manage starting pack'}).click();await page.locator('.pack-item').filter({hasText:'Welcome to {{project_name}}'}).getByRole('button',{name:'Edit',exact:true}).click();await page.locator('.modal [name=title]').fill('Your next chapter, {{project_name}}');await page.getByRole('button',{name:'Save template'}).click();await page.locator('.pack-item').filter({hasText:'Your next chapter'}).waitFor();await page.getByRole('button',{name:'Close dialog'}).click();
  await page.locator('[data-action=tab][data-tab=slides]').first().click();await page.getByRole('button',{name:'Add slide',exact:true}).click();await page.locator('[data-form=slide-editor]').waitFor();const manualTab=page.getByRole('tab',{name:'Add manually',exact:true}),templateTab=page.getByRole('tab',{name:'Add from studio template',exact:true});assert.equal(await manualTab.getAttribute('aria-selected'),'true');await page.locator('[data-form=slide-editor] [name=title]').fill('Keep my draft');await templateTab.click();assert.equal(await page.locator('[data-form=slide-editor]').isVisible(),false);await templateTab.press('ArrowLeft');assert.equal(await page.locator('[data-form=slide-editor] [name=title]').inputValue(),'Keep my draft');await manualTab.press('End');const systemTab=page.getByRole('tab',{name:'System slides',exact:true});assert.equal(await systemTab.getAttribute('aria-selected'),'true');await systemTab.press('ArrowLeft');assert.equal(await templateTab.getAttribute('aria-selected'),'true');const choicesToAdd=page.locator('[data-form=pack-add-slide] option');assert.equal(await choicesToAdd.count(),1);assert.match(await choicesToAdd.innerText(),/Let’s talk/);assert.equal(await page.locator('[data-form=slide-editor]').count(),1);await page.screenshot({path:path.join(artifacts,'add-slide-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'add-slide-mobile.png'),fullPage:true});assert.ok(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.getByRole('button',{name:'Add template slide',exact:true}).click();await page.locator('.modal').waitFor({state:'hidden'});d=await api('project&id='+pid);assert.equal(d.slide_content.find(s=>s.slide_id==='intro').title,'A personal welcome');assert.equal(d.slide_content.find(s=>s.slide_id==='contacts').title,'Let’s talk');
  await page.getByRole('button',{name:'Add slide',exact:true}).click();await page.locator('[data-form=slide-editor]').waitFor();await page.getByRole('tab',{name:'Add from studio template',exact:true}).click();assert.equal(await page.locator('.pack-slide-picker').count(),0);assert.match(await page.getByRole('tabpanel').innerText(),/No studio templates are available/);await page.getByRole('tab',{name:'Add manually',exact:true}).click();assert.equal(await page.locator('[data-form=slide-editor]').isVisible(),true);await page.getByRole('button',{name:'Close dialog'}).click();
  const clientEmail=`pack-client-${Date.now()}@example.test`;const shared=await api('share',{iteration:iid,emails:[clientEmail]});const clientContext=await browser.newContext({viewport:{width:390,height:844}});const client=await clientContext.newPage();client.on('pageerror',e=>errors.push(e.message));await clientContext.request.post(base+'/api.php?action=request_login',{data:{email:clientEmail}});const clientToken=fs.readFileSync(log,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];const login=await clientContext.request.post(base+'/api.php?action=consume_login',{data:{token:clientToken}});assert.ok(login.ok());page=client;await client.goto(base+'/client/projects/'+pid+'?iteration='+iid);await client.getByRole('button',{name:'Project documents',exact:true}).click();assert.match(await client.locator('.modal').innerText(),/Studio version 1/);await client.getByRole('button',{name:'Ask about documents'}).click();await client.locator('.modal [name=question]').fill('How many revision rounds are included?');await client.locator('.modal').getByRole('button',{name:'Send question'}).click();await client.locator('.modal .chat-message.assistant').waitFor();assert.match(await client.locator('.modal .chat-message.assistant').innerText(),/Two revision rounds/);await client.screenshot({path:path.join(artifacts,'documents-mobile.png'),fullPage:true});await client.locator('.modal [data-action=legal-citation]').first().click();assert.match(await client.locator('.extracted-text').innerText(),/Two revision rounds/);assert.deepEqual(errors,[]);
  console.log('PASS studio library, starter examples, PDF upload, wizard selection/back navigation, missing template selection, duplicate exclusion and preserved project edits, mobile layout, client documents and cited answers.');console.log('Screenshots: '+artifacts);
 }catch(e){if(page)await page.screenshot({path:path.join(artifacts,'failure.png'),fullPage:true});console.error('Screenshots: '+artifacts);throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
