<?php
declare(strict_types=1);
ob_start();$dir=sys_get_temp_dir().'/studiodeck-pages-'.bin2hex(random_bytes(5));mkdir($dir,0700,true);
putenv('DATABASE_PATH='.$dir.'/test.sqlite');putenv('WEBSITE_STORAGE_PATH='.$dir.'/sites');putenv('APP_ENV=local');putenv('APP_URL=http://localhost:8080');putenv('WEBSITE_LOCAL_FREE=true');
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/website_public.php';
function check(bool $ok,string $message): void {if(!$ok)throw new RuntimeException($message);echo "PASS $message\n";}
function denied(callable $fn,int $code=400): void {try{$fn();}catch(RuntimeException $e){check($e->getCode()===$code,'Denied '.$code.': '.$e->getMessage());return;}throw new RuntimeException('Expected denial');}
try{
 $uid=id();insert('users',['id'=>$uid,'email'=>'pages@example.test','name'=>'Studio','created_at'=>now()]);$sid=create_studio($uid,'Willow');$u=['user_id'=>$uid,'studio_id'=>$sid,'email'=>'pages@example.test'];
 $site=website_start($u,['template'=>'linen','revision'=>1]);$initial=json_decode($site['draft'],true);$initial['files']['script.js']='document.querySelector(".hero").dataset.original="yes";';$site=website_save($u,$initial,2);$legacy=json_decode($site['draft'],true);unset($legacy['pages']);$migrated=website_with_source($legacy);check(count($migrated['pages'])===1&&$migrated['pages'][0]['id']==='home'&&$migrated['files']===$legacy['files'],'Legacy source becomes Home without changing any source');
 $change=function(array $args)use($u,$sid){return website_page_change($u,$args+['revision'=>(int)website_get($sid)['revision']]);};
 $save=function(array $d)use($u,$sid){website_save($u,$d,(int)website_get($sid)['revision']);return website_payload($u)['draft'];};
 $result=$change(['operation'=>'add','kind'=>'contact','name'=>'Contact','slug'=>'contact','navigation'=>true]);$contact=$result['page'];$d=$result['website']['draft'];
 check(count($d['pages'])===2&&str_contains($d['files']['index.html'],'<!-- website:header -->')&&str_contains($d['files']['header.html'],'data-website-navigation'),'Adding the first page extracts one shared header and footer');
 check($d['files']['script.js']===''&&$d['files']['pages/home.js']===$legacy['files']['script.js'],'Existing Home interactions stay local when a shared layout is created');
 check(!$result['website']['checks']['errors'],'Home and Contact pass cross-page checks: '.json_encode($result['website']['checks']['errors']));
 $d['files']['header.html']=str_replace('Willow','Willow shared brand',$d['files']['header.html']);$d['files'][website_page_file($contact,'css')]='.contact-only {color: red;}';$d['files'][website_page_file($contact)]=str_replace('class="linen"','class="linen custom-contact"',$d['files'][website_page_file($contact)]);$d=$save($d);
 $home=website_page_files($d,website_page_find($d,'home'));$local=website_page_files($d,website_page_find($d,$contact));
 check(str_contains($local['index.html'],'class="linen custom-contact"'),'Custom page body classes survive shared theme assembly');
 check(str_contains($home['index.html'],'Willow shared brand')&&str_contains($local['index.html'],'Willow shared brand')&&!str_contains($home['styles.css'],'.contact-only')&&str_contains($local['styles.css'],'.contact-only'),'Shared edits reach every page; page CSS stays local');
 denied(fn()=>$change(['operation'=>'add','name'=>'Duplicate address','slug'=>'contact']));denied(fn()=>$change(['operation'=>'add','name'=>'Traversal','slug'=>'../secret']));denied(fn()=>$change(['operation'=>'add','name'=>'Reserved','slug'=>'assets/private']));denied(fn()=>$change(['operation'=>'delete','id'=>'home']));
 denied(fn()=>website_page_change($u,['operation'=>'delete','id'=>$contact,'revision'=>1]),409);
 $d['files']['index.html']=str_replace('</main>','<a href="/contact/#main">Reach us</a></main>',$d['files']['index.html']);$d=$save($d);
 $first=website_publish($u,(int)website_get($sid)['revision']);$root=website_dir($sid).'/releases/'.$first['id'].'/public';$published=file_get_contents($root.'/contact/index.html');
 check(is_file($root.'/contact/styles.css')&&str_contains($published,'href="../index.html"')&&str_contains($published,'http://localhost:8080/sites/'.$sid.'/contact/'),'Publish emits portable nested files with page-specific canonical URLs');
 check(substr_count(file_get_contents($root.'/sitemap.xml'),'<url>')===2,'Sitemap includes every enabled page');
 $result=$change(['operation'=>'update','id'=>$contact,'name'=>'Say hello','slug'=>'studio/contact','navigation'=>true]);$d=$result['website']['draft'];
 check(str_contains($d['files']['index.html'],'/studio/contact/#main')&&isset($d['files'][website_page_file($contact)]),'Renaming an address rewrites links without changing page identity');
 $second=website_publish($u,(int)website_get($sid)['revision']);check($second['redirects']['contact/index.html']==='studio/contact/index.html','Published old address redirects to new address');
 $copy=$change(['operation'=>'duplicate','id'=>$contact,'name'=>'Contact copy','slug'=>'contact-copy','navigation'=>false]);$copyId=$copy['page'];$d=$copy['website']['draft'];
 check($d['files'][website_page_file($copyId,'css')]===$d['files'][website_page_file($contact,'css')]&&!website_page_find($d,$copyId)['navigation'],'Duplicating copies local files and supports pages outside the menu');
 $moved=$change(['operation'=>'move','id'=>$contact,'direction'=>-1]);check($moved['website']['draft']['pages'][0]['id']===$contact,'Reordering pages controls navigation order');
 $deleted=$change(['operation'=>'delete','id'=>$contact]);$d=$deleted['website']['draft'];check(str_contains($d['files']['index.html'],'href="/">Reach us')&&!isset($d['files'][website_page_file($contact)]),'Deleting rewrites existing links to Home and removes page source');
 $third=website_publish($u,(int)website_get($sid)['revision']);check($third['redirects']['contact/index.html']==='index.html'&&$third['redirects']['studio/contact/index.html']==='index.html','Redirect chains survive later deletion');
 // Project pages use the website library, never the private project record.
 $image=imagecreatetruecolor(80,60);ob_start();imagepng($image);$bytes=ob_get_clean();imagedestroy($image);$asset=website_store_image($sid,$bytes);$pid=id();$quote=id();
 $d['projects'][]=['id'=>$pid,'source_id'=>'','slug'=>'house','title'=>'A public house','description'=>'Reviewed public description.','category'=>'Residential','location'=>'Amsterdam','included'=>true,'images'=>[['asset'=>$asset,'alt'=>'Sunny courtyard']]];
 $d['testimonials'][]=['id'=>$quote,'source_testimonial'=>'','project'=>$pid,'name'=>'Client','title'=>'Owner','content'=>'Approved words.','approved'=>true,'placement'=>'both','photo'=>'','video'=>''];$d=$save($d);
 $detail=$change(['operation'=>'add','name'=>'A public house','slug'=>'work/house','kind'=>'project','project'=>$pid]);$detailId=$detail['page'];$list=$change(['operation'=>'add','name'=>'Our projects','slug'=>'projects-list','kind'=>'projects','navigation'=>true]);$listId=$list['page'];$d=$list['website']['draft'];
 check(!$list['website']['checks']['errors'],'Project index and detail pages validate with approved materials: '.json_encode($list['website']['checks']['errors']));
 $detailHtml=website_page_files($d,website_page_find($d,$detailId))['index.html'];$listHtml=website_page_files($d,website_page_find($d,$listId))['index.html'];$homeHtml=website_page_files($d,website_page_find($d,'home'))['index.html'];
 check(str_contains($detailHtml,'Approved words.')&&str_contains($detailHtml,'<h1>A public house</h1>')&&str_contains($listHtml,'/work/house/')&&!str_contains($homeHtml,'data-project="'.$pid.'"'),'Details reuse approved text, photos and quotes; listings link to one project page');
 $d['projects'][0]['title']='Updated public title';$d['projects'][0]['description']='Updated public copy.';$d=$save($d);$detailHtml=website_page_files($d,website_page_find($d,$detailId))['index.html'];check(str_contains($detailHtml,'<h1>Updated public title</h1>')&&str_contains($detailHtml,'<title>Updated public title | Willow</title>'),'Library updates refresh project page content and SEO');
 $release=website_publish($u,(int)website_get($sid)['revision']);$root=website_dir($sid).'/releases/'.$release['id'].'/public';$html=file_get_contents($root.'/work/house/index.html');check(str_contains($html,'src="../../assets/')&&str_contains($html,'srcset="../../assets/')&&str_contains($html,'href="../../projects-list/"'),'Nested published images, responsive variants and links use portable relative paths');
 $d['projects'][0]['included']=false;$d=$save($d);$hidden=website_publish($u,(int)website_get($sid)['revision']);check(!isset($hidden['page_paths'][$detailId])&&$hidden['redirects']['work/house/index.html']==='index.html'&&!str_contains(website_page_files($d,website_page_find($d,$listId))['index.html'],'Updated public title'),'Hiding a project removes its detail page and listing from new releases');
 $d['projects'][0]['included']=true;$d=$save($d);
 // Scope boundaries are enforced independently of the model.
 $file=website_page_file($copyId);$before=$d['files'];$seen=[];
 $edited=website_chat_edit($u,['revision'=>(int)website_get($sid)['revision'],'page'=>$copyId,'scope'=>'page','prompt'=>'Add our opening hours'],function($system,$content)use(&$seen,$file){$seen=json_decode($content[0]['text'],true);return ['patches'=>[['file'=>$file,'find'=>'</main>','replace'=>'<p>Open weekdays.</p></main>']],'message'=>'Added hours.'];});
 check($seen['editable_files']===[$file,website_page_file($copyId,'css'),website_page_file($copyId,'js')]&&$edited['website']['draft']['files']['header.html']===$before['header.html'],'Page chat can edit only that page’s three files');
 denied(fn()=>website_chat_edit($u,['revision'=>(int)website_get($sid)['revision'],'page'=>$copyId,'scope'=>'page','prompt'=>'Cross scope'],fn()=>['files'=>['styles.css'=>'body{color:red}']]));
 $revision=(int)website_get($sid)['revision'];$clarified=website_chat_edit($u,['revision'=>$revision,'page'=>$copyId,'scope'=>'page','prompt'=>'Change every menu'],fn()=>['clarification'=>true,'message'=>'Switch to Shared design to change every menu.']);check((int)website_get($sid)['revision']===$revision,'Scope clarification saves no edits');
 $shared=website_chat_edit($u,['revision'=>$revision,'page'=>$copyId,'scope'=>'shared','prompt'=>'Change the brand'],fn()=>['patches'=>[['file'=>'header.html','find'=>'Willow shared brand','replace'=>'Willow worldwide']],'message'=>'Updated shared brand.']);check(str_contains(website_page_files($shared['website']['draft'],website_page_find($d,$copyId))['index.html'],'Willow worldwide'),'Shared chat updates the reusable header');
 // A broken secondary page cannot replace a working published site.
 $d=$shared['website']['draft'];$d['files'][$file]=str_replace('</main>','<a href="/missing/">Broken</a></main>',$d['files'][$file]);$save($d);$pointer=file_get_contents(website_dir($sid).'/current.json');denied(fn()=>website_publish($u,(int)website_get($sid)['revision']));check(file_get_contents(website_dir($sid).'/current.json')===$pointer,'A broken secondary page leaves the live release intact');
 // Restoring the complete saved snapshot follows the same save path as the API.
 $snapshot=json_decode(file_get_contents(website_dir($sid).'/releases/'.$first['id'].'/draft.json'),true);$restored=$save($snapshot);check(count($restored['pages'])===2&&website_page_find($restored,$contact)['slug']==='contact'&&$restored['files']===$snapshot['files'],'Whole-site restore recovers page order, addresses, shared design and source together');
 $restyled=website_start($u,['template'=>'noir','revision'=>(int)website_get($sid)['revision']]);$restyled=json_decode($restyled['draft'],true);$contactFiles=website_page_files($restyled,website_page_find($restyled,$contact));check(count($restyled['pages'])===2&&str_contains($contactFiles['index.html'],'class="noir custom-contact"')&&$restyled['files']['pages/home.js']!==$legacy['files']['script.js'],'Changing templates preserves other pages and their custom classes while replacing Home interactions');
 echo "Website page checks passed.\n";
}finally{website_remove_build($dir);}
