// Uses the isolated fixture exported by test_destinations.py. No external services.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
const base=process.env.STUDIODECK_TEST_URL,log=process.env.STUDIODECK_TEST_MAIL_LOG,fixture=JSON.parse(fs.readFileSync(process.env.STUDIODECK_TEST_EXPORT,'utf8'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});let page;const errors=[];
try{
 const login=async(email,entry='/')=>{const context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+entry);await page.locator('[name=email]').fill(email);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.locator('.login .notice').waitFor();const token=fs.readFileSync(log,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.getByRole('button',{name:'Continue',exact:true}).click();return page;};
 const menu=async()=>{await page.getByRole('button',{name:'Your account',exact:true}).click();};
 const switcher=async()=>{await menu();await page.getByRole('button',{name:'Switch workspace / project',exact:true}).click();await page.locator('.destination-shell').waitFor();};
 await login(fixture.emails.alpha);await page.locator('.destination-shell').waitFor();assert.equal(new URL(page.url()).pathname,'/choose');assert.equal(await page.locator('.destination-studio').count(),2);assert.equal(await page.locator('.destination-project').count(),2);
 const own=page.locator(`[data-destination-project="${fixture.a.project_id}"]`),other=page.locator(`[data-destination-project="${fixture.b.project_id}"]`);assert.ok(await own.getByRole('button',{name:'Open in studio'}).isVisible());assert.equal(await other.getByRole('button',{name:'Open in studio'}).count(),0);assert.match(await other.innerText(),/Iteration 01/);
 await own.locator('.destination-cover img').waitFor();await page.waitForFunction(()=>document.querySelector('.destination-cover img').naturalWidth>0);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const cover=await own.locator('.destination-cover').boundingBox(),photo=await own.locator('.destination-cover img').boundingBox(),copy=await own.locator('.destination-project-copy').boundingBox();assert.ok(photo.y+photo.height<=copy.y+1);assert.equal(cover.height,200);await page.screenshot({path:'/tmp/studiodeck-destinations-mobile.png'});await page.setViewportSize({width:1440,height:1000});
 await other.getByRole('button',{name:'Open presentation',exact:true}).click();await page.locator('.presentation').waitFor();assert.equal(await page.locator('.preview-bar').count(),0);assert.equal(await page.locator('[data-action=edit-slide]').count(),0);assert.equal(new URL(page.url()).pathname,'/client/projects/'+fixture.b.project_id);assert.equal(new URL(page.url()).searchParams.get('iteration'),fixture.b.iteration_id);
 await page.locator('.presentation-slide-navigation [data-action=next-slide]').click();await page.locator('.slide-outgoing').waitFor({state:'detached'});const slideUrl=page.url();await page.reload();await page.locator('.presentation').waitFor();assert.equal(page.url(),slideUrl);assert.equal(await page.locator('.preview-bar').count(),0);
 await page.goBack();await page.locator('.presentation').waitFor();assert.equal(new URL(page.url()).searchParams.get('slide'),'intro');
 await page.locator('[data-action=feedback]').click();await page.locator('[data-form=feedback] [name=body]').fill('A client comment from my other studio');await page.getByRole('button',{name:'Add comment',exact:true}).click();await page.locator('.comment-body').filter({hasText:'A client comment from my other studio'}).first().waitFor();await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await switcher();await page.locator(`[data-destination-project="${fixture.a.project_id}"]`).getByRole('button',{name:'Open in studio'}).click();await page.locator('#iteration-select').waitFor();assert.equal(new URL(page.url()).pathname,`/${fixture.studioA}/projects/${fixture.a.project_id}`);assert.equal(await page.locator('[data-action=new-studio]').count(),0);
 await page.locator('[data-action=iteration]').first().click();assert.ok(!(await page.locator('.modal').innerText()).includes('Earlier iterations'));assert.equal(await page.locator('.modal [data-action=switch-iteration]').count(),0);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 assert.equal(await page.locator('.sidebar [data-action=account-menu]').count(),0);await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('heading',{name:'Log out of Studiodeck?'}).waitFor();await page.getByRole('button',{name:'Stay signed in',exact:true}).click();await page.locator('.sidebar [data-action=projects]').first().click();await page.locator('#project-search').waitFor();
 await page.locator('#studio-select').selectOption(fixture.studioB);await page.locator('#project-search').waitFor();assert.equal(new URL(page.url()).pathname,`/${fixture.studioB}/projects`);assert.ok(!(await page.locator('#project-grid').innerText()).includes('Beta garden'));
 await page.goto(`${base}/client/projects/${fixture.a.project_id}?slide=${fixture.image.id}`);await page.locator('.slide-area img').first().waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.slide-area img')].some(im=>im.naturalWidth>0));
 // Direct links survive sign-in and refresh without an intermediate selection.
 await login(fixture.emails.client,`/client/projects/${fixture.b.project_id}?iteration=${fixture.b.iteration_id}&slide=budget`);await page.locator('.presentation-budget').waitFor();assert.equal(await page.locator('.destination-shell').count(),0);await page.reload();await page.locator('.presentation-budget').waitFor();await switcher();assert.equal(await page.locator('.destination-project').count(),2);
 await page.getByRole('button',{name:'Your account',exact:true}).click();await page.getByRole('button',{name:'Your profile',exact:true}).click();await page.locator('[data-form=profile]').waitFor();assert.equal(await page.locator('[data-form=profile] [name=name]').inputValue(),'Client Name');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 // A studio-only account has one destination and opens it directly.
 await login(fixture.emails.beta);await page.locator('#project-search').waitFor();assert.equal(new URL(page.url()).pathname,`/${fixture.studioB}/projects`);
 await login(fixture.emails.single);await page.locator('.presentation').waitFor();assert.equal(new URL(page.url()).pathname,'/client/projects/'+fixture.a.project_id);assert.equal(await page.locator('.preview-bar').count(),0);
 await login(fixture.emails.empty);await page.locator('.destination-shell').waitFor();assert.equal(await page.locator('.destination-project,.destination-studio').count(),0);assert.match(await page.locator('.destination-shell').innerText(),/No active projects/);
 // Anonymous shared URLs still work; account sign-in is optional.
 const anonymous=await browser.newContext();page=await anonymous.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(fixture.legacy);await page.locator('.presentation').waitFor();await menu();assert.ok(await page.getByRole('button',{name:'Sign in to see all your projects'}).isVisible());await page.getByRole('button',{name:'Your profile',exact:true}).click();await page.locator('[data-form=profile]').waitFor();
 assert.deepEqual(errors,[]);console.log('PASS Account selector, shared covers, mixed roles, studio/client navigation, direct-link login, refresh/back, comments/profile, single-destination routing, mobile and legacy client links.');
}catch(e){if(page)await page.screenshot({path:'/tmp/studiodeck-destinations-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
