// Run only against the isolated fixture produced by test_website_api.py.
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const fixture=JSON.parse(fs.readFileSync(process.env.WEBSITE_FIXTURE,'utf8'));
const base=process.env.STUDIODECK_TEST_URL||'http://127.0.0.1:18098';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});
try{
 const context=await browser.newContext({viewport:{width:1512,height:1000}});await context.addCookies(fixture.cookies);
 const get=async()=>await(await context.request.get(base+'/api.php?action=website')).json();
 const api=async(action,data)=>{const r=await context.request.post(base+'/api.php?action='+action,{headers:{'X-CSRF-Token':fixture.csrf},data});assert(r.ok(),await r.text());return r.json();};
 let site=await get();site=await api('website_reset',{revision:site.revision,confirm:true});site=await api('website_start',{revision:site.revision,template:'linen'});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/'+fixture.studio+'/website?edit=1');
 await page.getByLabel('Website page',{exact:true}).waitFor();assert.equal(await page.getByLabel('Website page',{exact:true}).inputValue(),'home');
 const preview=()=>page.frameLocator('.website-preview iframe');
 await page.getByRole('button',{name:'Add page',exact:true}).click();let form=page.locator('[data-form="website-page"]');await form.locator('[name="kind"]').selectOption('contact');await form.getByRole('button',{name:'Create page',exact:true}).click();await preview().getByRole('heading',{name:'Contact',exact:true}).waitFor();
 const contactId=await page.getByLabel('Website page',{exact:true}).inputValue();assert.notEqual(contactId,'home');
 await preview().getByRole('link',{name:'Home',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-website-page]').value==='home');await preview().getByRole('heading',{name:'Spaces made for living.'}).waitFor();
 await preview().getByRole('link',{name:'Contact',exact:true}).click();await preview().getByRole('heading',{name:'Contact',exact:true}).waitFor();
 console.log('PASS Page starters and preview navigation select the correct page');
 await page.getByRole('button',{name:'Code',exact:true}).click();await page.locator('.cm-content').waitFor();await page.getByRole('button',{name:'Page CSS',exact:true}).click();await page.locator('.cm-content').click();await page.keyboard.press('Control+a');await page.keyboard.insertText('body { --contact-test: 37; }');await page.getByRole('button',{name:'Save & preview',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.website-status').textContent.includes('Draft saved'));
 await preview().locator('body').waitFor();assert.equal((await preview().locator('body').evaluate(el=>getComputedStyle(el).getPropertyValue('--contact-test'))).trim(),'37');
 await page.getByRole('button',{name:'Shared design',exact:true}).click();await page.getByRole('button',{name:'header.html',exact:true}).click();await page.locator('.cm-content').waitFor();site=await get();const header=site.draft.files['header.html'].replace('Willow Studio','Shared studio brand');await page.locator('.cm-content').click();await page.keyboard.press('Control+a');await page.keyboard.insertText(header);await page.getByRole('button',{name:'Save & preview',exact:true}).click();await preview().getByRole('link',{name:'Shared studio brand',exact:true}).waitFor();
 await page.getByLabel('Website page',{exact:true}).selectOption('home');await preview().getByRole('link',{name:'Shared studio brand',exact:true}).waitFor();assert.equal((await preview().locator('body').evaluate(el=>getComputedStyle(el).getPropertyValue('--contact-test'))).trim(),'');
 await page.getByRole('button',{name:'Chat',exact:true}).click();assert.equal(await page.getByLabel('Edit scope').inputValue(),'page');await page.getByLabel('Edit scope').selectOption('shared');assert.equal(await page.getByLabel('Edit scope').inputValue(),'shared');
 console.log('PASS Page code stays local; shared header changes appear across pages and chat scopes are explicit');
 await page.getByRole('button',{name:'Manage pages',exact:true}).click();let card=page.locator('.website-page-card').filter({has:page.getByRole('heading',{name:'Contact',exact:true})});await card.getByRole('button',{name:'Page details',exact:true}).click();form=page.locator('[data-form="website-page"]');await form.locator('[name="name"]').fill('Say hello');await form.locator('[name="slug"]').fill('studio/hello');await form.getByRole('button',{name:'Save page details',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-website-page] option:checked').textContent==='Say hello');
 await page.getByRole('button',{name:'Manage pages',exact:true}).click();card=page.locator('.website-page-card').filter({has:page.getByRole('heading',{name:'Say hello',exact:true})});await card.getByRole('button',{name:'Duplicate',exact:true}).click();await page.locator('[data-form="website-page"]').getByRole('button',{name:'Create page',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-website-page] option:checked').textContent==='Say hello copy');
 await page.getByRole('button',{name:'Manage pages',exact:true}).click();card=page.locator('.website-page-card').filter({has:page.getByRole('heading',{name:'Say hello copy',exact:true})});await card.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete page',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('[data-website-page] option').length===3);
 console.log('PASS Rename, nested addresses, duplication, deletion and whole-draft undo work in the page manager');
 await page.getByRole('button',{name:'Add your projects & testimonials',exact:true}).click();await page.getByRole('button',{name:'Add project',exact:true}).click();await page.getByRole('button',{name:'Miller family',exact:true}).click();form=page.locator('[data-form="website-import"]');await form.locator(`[name="testimonial"][value="${fixture.testimonial}"]`).check();await form.getByRole('button',{name:'Add to draft',exact:true}).click();await page.getByRole('button',{name:'Add your projects & testimonials',exact:true}).click();await page.getByRole('button',{name:'Create project page',exact:true}).click();form=page.locator('[data-form="website-page"]');await form.getByRole('button',{name:'Create page',exact:true}).click();await preview().getByRole('heading',{name:'Miller family',exact:true}).waitFor();await preview().getByText('Our home finally feels like us.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Add page',exact:true}).click();form=page.locator('[data-form="website-page"]');await form.locator('[name="kind"]').selectOption('projects');await form.getByRole('button',{name:'Create page',exact:true}).click();await preview().getByRole('heading',{name:'Projects',exact:true}).waitFor();await preview().getByRole('link',{name:'Residential Miller family',exact:false}).count().then(async n=>{if(n)await preview().getByRole('link',{name:'Residential Miller family',exact:false}).click();else await preview().locator('.work-card').click();});await preview().getByRole('heading',{name:'Miller family',exact:true}).waitFor();
 console.log('PASS Project detail and listing starters share the reviewed website library and navigate correctly');
 await page.getByRole('button',{name:'Mobile',exact:true}).click();await preview().getByRole('button',{name:'Menu',exact:true}).click();await preview().getByRole('link',{name:'Say hello',exact:true}).click();await preview().getByRole('heading',{name:'Contact',exact:true}).waitFor();
 for(const width of [390,320]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'Manage pages',exact:true}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'Done',exact:true}).click();}
 await page.setViewportSize({width:1512,height:1000});await page.screenshot({path:'/tmp/website-pages-editor.png',fullPage:true});await page.getByRole('button',{name:'← Back to studio',exact:true}).click();await page.locator('[data-action="website-publish"]').click();await page.getByRole('button',{name:'Publish now',exact:true}).click();await page.locator('#toast').getByText('Your website is published.',{exact:true}).waitFor();
 const live=await context.newPage();await live.goto(base+'/sites/'+fixture.studio+'/');await live.getByRole('link',{name:'Say hello',exact:true}).click();assert(live.url().endsWith('/studio/hello/'));await live.getByRole('heading',{name:'Contact',exact:true}).waitFor();await live.getByRole('link',{name:'Projects',exact:true}).click();await live.locator('.work-card').click();await live.getByRole('heading',{name:'Miller family',exact:true}).waitFor();await live.setViewportSize({width:390,height:844});await live.getByRole('button',{name:'Menu',exact:true}).click();await live.getByRole('link',{name:'Home',exact:true}).click();assert(live.url().endsWith('/index.html'));assert(await live.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 console.log('PASS Mobile menus, editor controls, whole-site publication and public nested-page navigation work');assert.deepEqual(errors,[]);
}finally{await browser.close();}
