// Run against an isolated PHP server. No external playback or AI requests.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
const base=process.env.STUDIODECK_TEST_URL,mailLog=process.env.STUDIODECK_TEST_MAIL_LOG;
if(!base||!mailLog)throw Error('Set isolated STUDIODECK_TEST_URL and STUDIODECK_TEST_MAIL_LOG.');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});let page;try{
 page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('input[name=email]').fill(`compare-${Date.now()}@example.test`);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.waitForSelector('.login .notice');
 const token=fs.readFileSync(mailLog,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.reload();await page.getByRole('button',{name:'Continue'}).click();await page.waitForSelector('#project-search');
 const call=(action,data)=>page.evaluate(async({action,data})=>{const s=await(await fetch('/api.php?action=session')).json();const r=await fetch('/api.php?action='+action,{method:data?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json()};},{action,data});
 const session=(await call('session')).data,made=(await call('create_project',{name:'Comparison controls'})).data,iid=made.iteration_id;
 const project=`${base}/${session.studio.id}/projects/${made.project_id}`;


 const visual=await page.evaluate(async iid=>{const s=await(await fetch('/api.php?action=session')).json(),c=document.createElement('canvas');c.width=400;c.height=300;c.getContext('2d').fillRect(0,0,400,300);const blob=await new Promise(r=>c.toBlob(r)),form=new FormData();Object.entries({iteration:iid,type:'render',title:'Comparison render',section:'designs',situation:'concept'}).forEach(([k,v])=>form.set(k,v));form.set('image',blob,'render.png');const response=await fetch('/api.php?action=save_slide',{method:'POST',headers:{'X-CSRF-Token':s.csrf},body:form});if(!response.ok)throw Error(await response.text());return {id:(await response.json()).id,png:c.toDataURL().split(',')[1]};},iid);
 // Supply an existing generated variation without calling an image model.
 await page.route('**/api.php?**',async route=>{const action=new URL(route.request().url()).searchParams.get('action');if(['project','deck'].includes(action)){const response=await route.fetch(),deck=await response.json();const record=deck.slides?.find(s=>'visual-'+s.id===visual.id);if(record)record.image_version_id='test-generated';return route.fulfill({response,json:deck});}if(action==='slide_image')return route.fulfill({contentType:'image/png',body:Buffer.from(visual.png,'base64')});return route.continue();});
 await page.goto(`${base}/${session.studio.id}/slide/${visual.id}?project=${made.project_id}&iteration=${iid}`);await page.locator('[data-comparison-range]').waitFor();
 assert.equal(await page.locator('.slide-area [data-action=edit-slide]').count(),0);assert.equal(await page.locator('.preview-bar [data-action=edit-slide]').count(),1);
 const setDivider=async value=>page.locator('[data-comparison-range]').evaluate((input,value)=>{input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));},value);
 await setDivider(82);await page.locator('[data-action=toggle-slide-comparison]').click();assert.equal(await page.locator('[data-comparison-range]').count(),0);await page.getByRole('button',{name:'Compare original & generated',exact:true}).click();assert.equal(await page.locator('[data-comparison-range]').inputValue(),'50');assert.equal(await page.locator('[data-comparison]').evaluate(el=>el.style.getPropertyValue('--comparison')),'50%');
 await setDivider(17);await page.getByRole('button',{name:'Show original',exact:true}).click();await page.getByRole('button',{name:'Compare original & generated',exact:true}).click();assert.equal(await page.locator('[data-comparison-range]').inputValue(),'50');
 await page.locator('.presentation-sidebar-handle').hover();await page.locator('[data-action=toggle-fullscreen]').click();await page.waitForFunction(()=>document.body.classList.contains('presentation-fullscreen'));assert.equal(await page.locator('[data-action=edit-slide]:visible').count(),0);await page.locator('#main').focus();await page.keyboard.press('Escape');
 const shared=(await call('share',{iteration:iid,emails:['client@example.test']})).data.links[0];await page.goto(`${base}/?slide=${visual.id}#/view/${shared.url.split('/#/view/')[1]}`);await page.locator('[data-comparison-range]').waitFor();assert.equal(await page.locator('[data-action=edit-slide]').count(),0);await setDivider(90);await page.locator('[data-action=toggle-slide-comparison]').click();await page.getByRole('button',{name:'Compare original & generated',exact:true}).click();assert.equal(await page.locator('[data-comparison-range]').inputValue(),'50');
 assert.deepEqual(errors,[]);console.log('PASS Reopening original/generated comparison resets divider to center; Edit slide appears only in editor bar, never on slides or client/fullscreen views.');
}catch(e){if(page)await page.screenshot({path:'/tmp/studiodeck-comparison-controls-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
