import assert from 'node:assert/strict';
import {billingUi} from '../public/assets/billing.js';
let queued=[],calls=[],messages=[],resumed=0,status='pending';
globalThis.location={search:'?checkout=failed&order=order-1',pathname:'/test/billing'};
globalThis.history={replaceState(){}};
globalThis.setTimeout=fn=>{queued.push(fn);return queued.length;};
globalThis.clearTimeout=()=>{};
const state={studio:{id:'test',role:'admin'},tab:'billing'};
const api=async action=>{
  calls.push(action);
  if(action==='billing')return {summary:{},orders:[{id:'order-1',status}]};
  if(action==='billing_invoices')return {invoices:[]};
  return {ok:true};
};
const billing=billingUi({state,api,render(){},toast:m=>messages.push(m),resumeAccess:async()=>resumed++});
await billing.returned();
assert(calls.includes('billing_refresh'),'Decline returns refresh billing');
assert.equal(queued.length,1,'Pending webhook delivery is polled');
assert.equal(resumed,0,'Unverified return parameters never grant access');
status='failed';await queued.shift()();
assert.equal(queued.length,0,'Polling stops once failure is confirmed');
assert(messages.at(-1).includes('Payment declined'));
assert(messages.at(-1).includes('Existing trial, paid or legacy access'));
assert.equal(resumed,0);
location.search='?checkout=cancelled';calls=[];await billing.returned();
assert(calls.includes('billing_refresh'),'Cancellation return also refreshes stale order state');
location.search='?checkout=success&order=order-1';status='paid';await billing.returned();
assert.equal(resumed,1,'Only confirmed paid orders resume project access');
assert.equal(queued.length,0,'Successful return does not start redundant polling');
console.log('PASS declined, delayed, cancelled and successful checkout return flows.');
