import fs from 'node:fs';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const fixture=JSON.parse(fs.readFileSync(process.env.WEBSITE_FIXTURE,'utf8'));
const base=process.env.STUDIODECK_TEST_URL||'http://127.0.0.1:18098';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});
try{
 const context=await browser.newContext({viewport:{width:1512,height:1000}});await context.addCookies(fixture.cookies);
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>{if(!e.message.includes('Intentional preview failure'))errors.push(e.message)});
 await page.goto(base+'/'+fixture.studio+'/website');await page.getByRole('heading',{name:'Good work deserves a beautiful home.'}).waitFor();
 await page.screenshot({path:'/tmp/website-welcome.png',fullPage:true});
 await page.getByRole('button',{name:'Find your starting point'}).click();
 assert.equal(await page.locator('.website-example-card').count(),10);
 await page.locator('.website-example-card iframe').first().waitFor();await page.waitForTimeout(1500);
 await page.screenshot({path:'/tmp/website-gallery.png',fullPage:true});
 for(const id of ['editorial','linen','noir','gallery','coast','atelier','panorama','folio','terracotta','minimal']){
  await page.locator(`[data-action="website-example"][data-template="${id}"]`).click();
  const frame=page.frameLocator('.website-full-example');await frame.getByRole('heading',{name:'Spaces that stay with you.'}).waitFor();
  const handle=await page.locator('.website-full-example').elementHandle(),actual=await handle.contentFrame();
  assert.equal(await actual.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true,id+' desktop overflow');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await actual.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true,id+' mobile overflow');
  await page.setViewportSize({width:1512,height:1000});
  if(id==='noir')await page.screenshot({path:'/tmp/website-example-noir.png',fullPage:true});
  await page.getByRole('button',{name:'All designs',exact:true}).click();
 }
 console.log('PASS Ten full-screen examples render at desktop and mobile sizes');
 await page.locator('[data-action="website-choose-template"][data-template="linen"]').click();
 await page.getByRole('heading',{name:'Your work. Your website.'}).waitFor();
 await page.frameLocator('.website-preview iframe').getByRole('heading',{name:'Spaces made for living.'}).waitFor();
 await page.locator('[data-action="website-tab"][data-tab="source"]').click();
 let input=page.getByRole('textbox',{name:'index.html source',exact:true});
 const html=(await input.inputValue()).replaceAll('Spaces made for living.','Thoughtful spaces, made for you.').replace('</main>','<section id="custom"><h2>Entirely our own</h2><button id="try-it">Try this interaction</button><p id="result"></p></section></main>');
 await input.fill(html);
 await page.locator('[data-action="website-file"][data-file="styles.css"]').click();
 input=page.getByRole('textbox',{name:'styles.css source',exact:true});await input.fill((await input.inputValue())+'\n#custom { padding: 40px 0; } #try-it { padding: 14px; background: #453b2f; color: white; border: 0; }');
 await page.locator('[data-action="website-file"][data-file="script.js"]').click();
 await page.getByRole('textbox',{name:'script.js source',exact:true}).fill(`document.getElementById('try-it').onclick=()=>document.getElementById('result').textContent='It works!';try{document.cookie;document.body.dataset.cookies='exposed'}catch(e){document.body.dataset.cookies='blocked'}try{parent.document.body;document.body.dataset.parent='exposed'}catch(e){document.body.dataset.parent='blocked'}`);
 await page.getByRole('button',{name:'Save & preview',exact:true}).click();
 let preview=page.frameLocator('.website-preview iframe');await preview.getByRole('heading',{name:'Thoughtful spaces, made for you.'}).waitFor();
 await preview.getByRole('button',{name:'Try this interaction'}).click();await preview.getByText('It works!',{exact:true}).waitFor();
 assert.equal(await preview.locator('body').getAttribute('data-cookies'),'blocked');assert.equal(await preview.locator('body').getAttribute('data-parent'),'blocked');
 assert.equal(await page.locator('.website-preview iframe').evaluate(frame=>frame.contentDocument),null);
 console.log('PASS Free HTML/CSS/JS edits work and the preview cannot access workspace cookies or DOM');
 await page.getByRole('textbox',{name:'script.js source',exact:true}).fill('throw new Error("Intentional preview failure")');
 await page.getByRole('button',{name:'Save & preview',exact:true}).click();
 await page.locator('[data-action="website-publish"]').click();
 await page.getByText('Uncaught Error: Intentional preview failure',{exact:false}).last().waitFor();
 assert.equal(await page.locator('[data-action="website-confirm-publish"]').isDisabled(),true);
 await page.getByRole('button',{name:'Keep editing',exact:true}).click();await page.locator('[data-action="website-undo"]').click();
 await preview.getByRole('button',{name:'Try this interaction'}).click();await preview.getByText('It works!',{exact:true}).waitFor();
 console.log('PASS Broken JavaScript blocks the publish confirmation and Undo restores working source');
 await page.locator('[data-action="website-tab"][data-tab="testimonials"]').click();await page.getByRole('button',{name:'Add a testimonial'}).click();
 const form=page.locator('[data-form="website-testimonial"]');await form.locator('[name="name"]').fill('Robin');await form.locator('[name="content"]').fill('Our home finally feels like us.');await form.locator('[name="approved"]').check();await form.getByRole('button',{name:'Save testimonial'}).click();
 await preview.getByText('Our home finally feels like us.',{exact:false}).first().waitFor();await preview.getByRole('heading',{name:'Entirely our own'}).waitFor();
 await preview.getByRole('button',{name:'Try this interaction'}).click();await preview.getByText('It works!',{exact:true}).waitFor();
 console.log('PASS Adding testimonials preserves custom design and interactions');
 await page.locator('[data-action="website-publish"]').click();await page.locator('[data-action="website-confirm-publish"]').click();await page.locator('#toast').getByText('Your website is published.',{exact:true}).waitFor();
 const live=await context.newPage();await live.goto(base+'/sites/'+fixture.studio+'/');await live.getByRole('heading',{name:'Thoughtful spaces, made for you.'}).waitFor();
 await live.getByRole('button',{name:'Try this interaction'}).click();await live.getByText('It works!',{exact:true}).waitFor();
 assert.equal(await live.locator('body').getAttribute('data-cookies'),'blocked');
 await live.locator('img').evaluateAll(imgs=>{for(const i of imgs)i.loading='eager'});await live.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));
 console.log('PASS Explicit publishing serves working static HTML/CSS/JS with optimized images');
 await page.screenshot({path:'/tmp/website-editor-desktop.png',fullPage:true});await live.screenshot({path:'/tmp/website-public-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/website-editor-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Editor overflows mobile viewport');
 await live.setViewportSize({width:390,height:844});assert(await live.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Public website overflows mobile viewport');

 await page.getByRole('button',{name:'Start from scratch',exact:true}).click();
 await page.getByRole('button',{name:'Keep my website',exact:true}).click();
 await page.getByRole('heading',{name:'Your work. Your website.'}).waitFor();
 await page.getByRole('button',{name:'Start from scratch',exact:true}).click();
 await page.getByRole('button',{name:'Remove website & start over',exact:true}).click();
 await page.getByRole('heading',{name:'Good work deserves a beautiful home.'}).waitFor();
 const removed=await live.reload();assert.equal(removed.status(),404);
 await page.reload();await page.getByRole('heading',{name:'Good work deserves a beautiful home.'}).waitFor();
 await page.getByRole('button',{name:'Find your starting point'}).click();assert.equal(await page.locator('.website-example-card').count(),10);
 console.log('PASS Reset can be cancelled or confirmed, removes the live website, and returns to the starting gallery');
 assert.deepEqual(errors,[]);console.log('PASS Mobile layouts and no browser errors');
}finally{await browser.close();}
