// Run against an isolated PHP server. No external playback or AI requests.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
const base=process.env.STUDIODECK_TEST_URL,mailLog=process.env.STUDIODECK_TEST_MAIL_LOG;
if(!base||!mailLog)throw Error('Set isolated STUDIODECK_TEST_URL and STUDIODECK_TEST_MAIL_LOG.');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});let page;try{
 page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('input[name=email]').fill(`people-${Date.now()}@example.test`);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.waitForSelector('.login .notice');
 const token=fs.readFileSync(mailLog,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.reload();await page.getByRole('button',{name:'Continue'}).click();await page.waitForSelector('#project-search');
 const call=(action,data)=>page.evaluate(async({action,data})=>{const s=await(await fetch('/api.php?action=session')).json();const r=await fetch('/api.php?action='+action,{method:data?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json()};},{action,data});
 const session=(await call('session')).data,made=(await call('create_project',{name:'People settings'})).data,iid=made.iteration_id;
 const project=`${base}/${session.studio.id}/projects/${made.project_id}`;

 const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=120;c.height=80;c.getContext('2d').fillRect(0,0,120,80);return c.toDataURL().split(',')[1];}),'base64');
 const file={name:'portrait.png',mimeType:'image/png',buffer:png};
 await page.getByRole('button',{name:'User profile',exact:true}).click();await page.locator('[data-form=profile]').waitFor();
 assert.equal(await page.locator('[name=use_color],[name=color],[data-action=help]').count(),0);assert.ok(!(await page.locator('.profile-page').innerText()).includes('Email delivery'));
 const avatarInput=page.locator('[data-form=avatar] input[type=file]');await avatarInput.setInputFiles({name:'too-large.png',mimeType:'image/png',buffer:Buffer.alloc(2*1024*1024+1)});assert.match(await page.locator('[data-image-upload-status]').innerText(),/up to 2 MB/);assert.ok(await page.getByRole('button',{name:'Save avatar',exact:true}).isDisabled());
 // Browse through the preview button and save a rectangular source as a circular avatar.
 const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose avatar photo'}).click();await (await chooser).setFiles(file);await page.waitForFunction(()=>!document.querySelector('[data-form=avatar] [type=submit]').disabled);assert.equal(await page.locator('.upload-selection').count(),0);
 await page.getByRole('button',{name:'Save avatar',exact:true}).click();await page.locator('.profile-open .avatar img').waitFor();
 const checkAvatars=async()=>{const styles=await page.locator('.avatar').evaluateAll(els=>els.map(el=>({w:el.getBoundingClientRect().width,h:el.getBoundingClientRect().height,r:getComputedStyle(el).borderRadius,b:parseFloat(getComputedStyle(el).borderTopWidth)})));assert.ok(styles.length);for(const style of styles){assert.equal(style.r,'50%');assert.ok(style.b>=1);assert.ok(Math.abs(style.w-style.h)<1);}};await checkAvatars();
 await page.locator('[data-form=profile] [name=name]').fill('Alex Designer');await page.locator('[name=email_comments]').uncheck();await page.getByRole('button',{name:'Save profile',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.profile-open').textContent.includes('Alex Designer'));assert.equal((await call('profile')).data.profile.email_comments,false);
 assert.equal((await call('save_profile',{name:'Alex Designer',email_comments:false,color:'#ff0000'})).data.profile.color,'');
 await page.getByRole('button',{name:'Studio settings',exact:true}).click();await page.locator('[data-form=studio-logo]').waitFor();
 const drop=async(selector,fileData)=>page.locator(selector).evaluate((zone,base64)=>{const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),transfer=new DataTransfer();transfer.items.add(new File([bytes],'logo.png',{type:'image/png'}));zone.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));},fileData);
 await drop('[data-image-upload=logo]',png.toString('base64'));await page.waitForFunction(()=>!document.querySelector('[data-form=studio-logo] [type=submit]').disabled);
 for(const zone of await page.locator('.project-logo-dropzone').all()){assert.equal(await zone.evaluate(el=>getComputedStyle(el).borderTopStyle),'dashed');assert.equal(await zone.evaluate(el=>getComputedStyle(el).borderRadius),'14px');}
 await page.getByRole('button',{name:'Save logo',exact:true}).click();await page.locator('.sidebar .studio-logo').waitFor();await page.locator('[data-image-upload-preview] .studio-logo').waitFor();await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await call('save_studio_user',{name:'Bert Builder',email:'bert@example.test',role:'member'});await call('save_studio_user',{name:'Clara Architect',email:'clara@example.test',role:'member'});
 await page.getByRole('button',{name:'Studio users',exact:true}).click();await page.locator('#studio-user-search').waitFor();assert.equal(await page.locator('.member-row').count(),3);assert.equal(await page.locator('.member-row .avatar img').count(),1);await checkAvatars();
 const search=page.getByRole('searchbox',{name:'Search studio users'});await search.fill('BERT');assert.equal(await page.locator('.member-row').count(),1);assert.match(await page.locator('.member-row').innerText(),/Bert Builder/);await search.fill('clara@example');assert.equal(await page.locator('.member-row').count(),1);await search.fill('nobody');assert.equal(await page.locator('.member-row').count(),0);assert.match(await page.locator('#studio-user-count').innerText(),/0 of 3/);await search.fill('');assert.equal(await page.locator('.member-row').count(),3);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.waitForTimeout(350);await page.screenshot({path:'/tmp/studiodeck-people-mobile.png'});
 // Shared client preferences use the same upload field without personal color controls.
 const shared=(await call('share',{iteration:iid,emails:['client@example.test']})).data.links[0];await page.goto(`${base}/#/view/${shared.url.split('/#/view/')[1]}`);await page.locator('[data-action=account-menu]').click();await page.getByRole('button',{name:'Your profile',exact:true}).click();await page.locator('[data-form=profile]').waitFor();assert.equal(await page.locator('[name=use_color],[name=color]').count(),0);await drop('[data-image-upload=avatar]',png.toString('base64'));await page.waitForFunction(()=>!document.querySelector('[data-form=avatar] [type=submit]').disabled);await page.getByRole('button',{name:'Save avatar',exact:true}).click();await page.locator('.profile-page [data-image-upload-preview] img').waitFor();await checkAvatars();
 assert.deepEqual(errors,[]);console.log('PASS Avatar browse/drop, validation, persistence, studio logo drop/save, circular avatars, profile preferences without custom color, member avatars/search and mobile/client profiles.');
}catch(e){if(page)await page.screenshot({path:'/tmp/studiodeck-people-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
