// Run against an isolated test server/worker with log-only email and no AI key.
// Set STUDIODECK_TEST_URL and STUDIODECK_TEST_MAIL_LOG to that fixture.
// Optional: PLAYWRIGHT_MODULE and CHROMIUM_EXECUTABLE for local browser installs.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict'),path=require('path'),os=require('os');
const base=process.env.STUDIODECK_TEST_URL,mailLog=process.env.STUDIODECK_TEST_MAIL_LOG;
if(!base||!mailLog)throw Error('Set STUDIODECK_TEST_URL and STUDIODECK_TEST_MAIL_LOG for an isolated test fixture.');
const root=path.resolve(__dirname,'..'),artifacts=fs.mkdtempSync(path.join(os.tmpdir(),'studiodeck-wizard-'));
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:false,args:['--no-sandbox','--headless=new']});let page;try{
page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let creates=0;page.on('request',r=>{if(r.url().includes('action=create_project'))creates++;});
await page.goto(base);await page.locator('input[name=email]').fill(`wizard-${Date.now()}@example.test`);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.waitForSelector('.login .notice');const token=fs.readFileSync(mailLog,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.reload();await page.getByRole('button',{name:'Open my studio'}).click();await page.waitForSelector('#project-search');
await page.getByRole('button',{name:'New project',exact:true}).click();assert.equal(await page.locator('.project-wizard-steps [aria-current]').innerText(),'1\nProject details');await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(creates,0);
await page.getByRole('button',{name:'New project',exact:true}).click();await page.locator('[name=name]').fill('Wizard design');await page.locator('[name=emails]').fill('client@example.test\npartner@example.test');await page.locator('[name=location]').fill('Amsterdam');await page.getByRole('button',{name:'Next: upload files',exact:true}).click();assert.equal(creates,0);assert.ok(await page.getByRole('button',{name:'Create & process files',exact:true}).isDisabled());
await page.locator('#wizard-file-input').setInputFiles([path.join(root,'public/assets/example-budget.csv'),path.join(root,'public/assets/concept-plan.pdf')]);assert.equal(await page.locator('.wizard-file-row').count(),2);await page.getByRole('button',{name:'Back',exact:true}).click();assert.equal(await page.locator('[name=location]').inputValue(),'Amsterdam');await page.getByRole('button',{name:'Next: upload files',exact:true}).click();assert.equal(await page.locator('.wizard-file-row').count(),2);await page.getByRole('button',{name:'Remove concept-plan.pdf',exact:true}).click();assert.equal(await page.locator('.wizard-file-row').count(),1);
await page.locator('[data-wizard-dropzone]').evaluate(el=>{const dt=new DataTransfer();dt.items.add(new File(['bad'],'notes.exe'));el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));});assert.match(await page.locator('.form-error').innerText(),/isn’t a supported file/);assert.equal(await page.locator('.wizard-file-row').count(),1);assert.equal(creates,0);
await page.screenshot({path:path.join(artifacts,'files.png')});
let failOnce=true;await page.route('**/api.php?action=upload',r=>{if(failOnce){failOnce=false;return r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Upload interrupted. Please try again.'})});}return r.continue();});
await page.getByRole('button',{name:'Create & process files',exact:true}).click();await page.getByRole('button',{name:'Retry upload',exact:true}).waitFor();assert.equal(creates,1);assert.equal(await page.locator('.wizard-file-row').count(),1);assert.match(await page.locator('.form-error').innerText(),/Upload interrupted/);
await page.getByRole('button',{name:'Retry upload',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent==='Your project is ready to explore.',{},{timeout:120000});assert.equal(creates,1);assert.equal(await page.locator('#processing-overlay').count(),0);assert.ok(await page.locator('.overview-grid').isVisible());assert.match(page.url(),/\/projects\/[a-z0-9]+/);
const project=await page.evaluate(async()=>{const id=location.pathname.split('/').at(-1);return await(await fetch('/api.php?action=project&id='+id)).json();});assert.equal(project.files.length,1);assert.ok(project.jobs.every(j=>j.status==='done'));assert.equal(project.contacts.filter(c=>c.role==='Client').length,2);
await page.getByRole('button',{name:'All projects',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'New project',exact:true}).click();await page.locator('[name=name]').fill('Files later');await page.getByRole('button',{name:'Next: upload files',exact:true}).click();await page.screenshot({path:path.join(artifacts,'mobile.png')});const box=await page.locator('.modal').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390);await page.getByRole('button',{name:'Add files later',exact:true}).click();await page.locator('.overview-grid').waitFor();assert.equal(creates,2);assert.equal(await page.locator('.modal').count(),0);assert.deepEqual(errors,[]);console.log('PASS wizard cancellation, details/back navigation, file selection/removal/validation, upload retry without duplicates, real processing and automatic project overview, mobile skip-upload.');
}catch(e){if(page)await page.screenshot({path:path.join(artifacts,'failure.png')});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
