// Isolated PHP server; YouTube iframe responses are stubbed, no external playback or AI requests.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
const base=process.env.STUDIODECK_TEST_URL,mailLog=process.env.STUDIODECK_TEST_MAIL_LOG;
if(!base||!mailLog)throw Error('Set isolated STUDIODECK_TEST_URL and STUDIODECK_TEST_MAIL_LOG.');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});let page;try{
 page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],embeds=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://www.youtube-nocookie.com/**',route=>{embeds.push(route.request().url());return route.fulfill({contentType:'text/html',body:'<!doctype html><title>YouTube player fixture</title><button>Pause</button>'});});
 await page.goto(base);await page.locator('input[name=email]').fill(`video-${Date.now()}@example.test`);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.waitForSelector('.login .notice');
 const token=fs.readFileSync(mailLog,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.reload();await page.getByRole('button',{name:'Continue'}).click();await page.waitForSelector('#project-search');
 const call=(action,data)=>page.evaluate(async({action,data})=>{const s=await(await fetch('/api.php?action=session')).json();const r=await fetch('/api.php?action='+action,{method:data?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json()};},{action,data});
 const session=(await call('session')).data,made=(await call('create_project',{name:'Video presentation'})).data,iid=made.iteration_id;
 const project=`${base}/${session.studio.id}/projects/${made.project_id}`;
 await page.goto(project+'?tab=slides');await page.getByRole('button',{name:'Add slide',exact:true}).click();await page.locator('[data-manual-type]').selectOption('video');
 assert.equal(await page.locator('[data-slide-image-fields]').isVisible(),false);assert.ok(await page.locator('[name=video_url]').isVisible());
 await page.locator('.modal [name=title]').fill('A tour of the design');await page.locator('[name=video_url]').fill('https://example.com/not-youtube');await page.getByRole('button',{name:'Create slide',exact:true}).click();await page.locator('.form-error').waitFor();assert.match(await page.locator('.form-error').innerText(),/YouTube/);
 await page.locator('[name=video_url]').fill('https://youtu.be/M7lc1UVf-VE?t=90');await page.locator('.modal [name=description]').fill('Walk through the proposed space.');await page.getByRole('button',{name:'Create slide',exact:true}).click();await page.locator('.modal').waitFor({state:'detached'});
 let row=page.locator('.slide-editor-row').filter({hasText:'A tour of the design'});await row.waitFor();assert.match(await row.innerText(),/Video · YouTube/);assert.equal(await row.locator('.video-thumbnail').count(),1);
 const slideId=await row.getAttribute('data-slide-id');await row.locator('[data-action=edit-slide]').click();assert.equal(await page.locator('[name=video_url]').inputValue(),'https://www.youtube.com/watch?v=M7lc1UVf-VE&t=90');await page.locator('.modal [name=section]').selectOption('designs');await page.locator('.modal [name=title]').fill('Our design film');await page.getByRole('button',{name:'Save slide',exact:true}).click();await page.locator('.modal').waitFor({state:'detached'});
 row=page.locator(`.slide-editor-row[data-slide-id="${slideId}"]`);await row.locator('[data-action=visibility-slide]').click();await page.waitForFunction(id=>document.querySelector(`[data-slide-id="${id}"]`)?.classList.contains('is-hidden'),slideId);await row.locator('[data-action=visibility-slide]').click();await page.waitForFunction(id=>!document.querySelector(`[data-slide-id="${id}"]`)?.classList.contains('is-hidden'),slideId);
 await row.locator('[data-action=open-editor-slide]').click();await page.locator('.video-slide').waitFor();const savedUrl=page.url();assert.equal(await page.locator('iframe').count(),0);assert.equal(embeds.length,0);assert.equal(await page.locator('.video-slide [data-action=enhance-slide]').count(),0);
 await page.getByRole('button',{name:'Play video: Our design film',exact:true}).click();await page.frameLocator('iframe[data-youtube-player]').getByRole('button',{name:'Pause'}).waitFor();assert.equal(embeds.length,1);assert.match(embeds[0],/embed\/M7lc1UVf-VE\?autoplay=1.*start=90/);
 // Moving away destroys the player and never loads another iframe in the animation copy.
 await page.locator('.slide-area').focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(400);assert.equal(await page.locator('iframe[data-youtube-player]').count(),0);assert.equal(embeds.length,1);
 await page.goto(savedUrl);await page.locator('.video-slide').waitFor();assert.equal(await page.locator('iframe').count(),0);assert.equal(await page.locator('.video-slide h1').innerText(),'Our design film');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-action=toggle-fullscreen]').click();await page.waitForFunction(()=>document.body.classList.contains('presentation-fullscreen'));
 const heading=await page.locator('.video-slide h1').boundingBox(),chrome=await page.locator('.presentation-chrome-top').evaluate(el=>el.offsetHeight);assert.ok(heading.y>chrome);const player=await page.locator('.video-player').boundingBox();assert.ok(player.width>=200&&player.height>=200&&player.x+player.width<=390);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/studiodeck-youtube-mobile.png'});
 await page.keyboard.press('Escape');await page.goto(project+'?tab=slides');
 const bad=await call('save_slide',{iteration:iid,type:'video',title:'Unsafe',video_url:'https://youtube.com.evil.test/watch?v=M7lc1UVf-VE'});assert.equal(bad.status,400);
 const shared=(await call('share',{iteration:iid,emails:['client@example.test']})).data.links[0];const next=(await call('new_iteration',{iteration:iid,title:'Next film'})).data.id;
 const changed=await call('save_slide',{iteration:next,slide_id:slideId.slice(7),type:'video',title:'A revised film',video_url:'https://www.youtube.com/shorts/aqz-KE-bpKQ'});assert.equal(changed.status,200);
 await page.goto(`${base}/?slide=${slideId}#/view/${shared.url.split('/#/view/')[1]}`);await page.locator('.video-slide').waitFor();assert.equal(await page.locator('.video-slide h1').innerText(),'Our design film');assert.equal(await page.locator('[data-play-youtube]').getAttribute('data-play-youtube'),'M7lc1UVf-VE');assert.equal(await page.locator('[data-action=edit-slide]').count(),0);
 await page.locator('[data-play-youtube]').click();await page.frameLocator('iframe[data-youtube-player]').getByRole('button',{name:'Pause'}).waitFor();assert.deepEqual(errors,[]);
 console.log('PASS YouTube slide create/edit/validation, group, visibility, saved URL, click-to-load embed, stop on navigation, no duplicate players, fullscreen/mobile, sharing and iteration isolation.');
}catch(e){if(page)await page.screenshot({path:'/tmp/studiodeck-youtube-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
