// Isolated app, log-only email. No real messages or AI calls.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
const base=process.env.STUDIODECK_TEST_URL,mailLog=process.env.STUDIODECK_TEST_MAIL_LOG;
if(!base||!mailLog)throw Error('Set an isolated STUDIODECK_TEST_URL and STUDIODECK_TEST_MAIL_LOG.');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:false,args:['--no-sandbox','--headless=new']});try{
 const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('input[name=email]').fill(`settings-${Date.now()}@example.test`);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.waitForSelector('.login .notice');const token=fs.readFileSync(mailLog,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.reload();await page.getByRole('button',{name:'Continue'}).click();await page.waitForSelector('#project-search');
 const made=await page.evaluate(async()=>{const s=await(await fetch('/api.php?action=session')).json();const post=async(action,body)=>await(await fetch('/api.php?action='+action,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:JSON.stringify(body)})).json();const p=await post('create_project',{name:'Settings test'});await post('project_settings',{project_id:p.project_id,deadline:'2027-01-23',tags:['Original']});return {...p,studio:s.studio.id};});
 const deck=()=>page.evaluate(async pid=>await(await fetch('/api.php?action=project&id='+pid)).json(),made.project_id);
 await page.goto(`${base}/${made.studio}/projects/${made.project_id}`);await page.getByRole('button',{name:'Project settings',exact:true}).click();
 const modal=page.locator('.modal'),form=modal.locator('[data-form=project-settings]');
 assert.equal(await modal.locator('input[type=date],select[name=visibility],[data-action=delete-project],[data-action=project-team],[data-action=theme]').count(),0);
 await page.screenshot({path:'/tmp/studiodeck-project-settings.png'});
 assert.equal(await form.evaluate(el=>el.lastElementChild.className),'modal-footer');assert.ok(await modal.getByRole('switch',{name:'Team members only'}).isChecked());
 await modal.getByRole('button',{name:'How the presentation logo is chosen'}).focus();assert.ok(await modal.getByRole('tooltip').isVisible());
 const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=120;c.height=60;const ctx=c.getContext('2d');ctx.fillStyle='#68724c';ctx.fillRect(0,0,120,60);return c.toDataURL().split(',')[1];}),'base64');
 assert.equal(await form.locator('[name=tags]').count(),0);await modal.getByRole('switch',{name:'Team members only'}).uncheck();
 const chooser=page.waitForEvent('filechooser');await modal.getByRole('button',{name:'Choose presentation logo'}).click();await(await chooser).setFiles({name:'logo.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>document.querySelector('[data-logo-status]')?.textContent.includes('Ready to save'));
 await modal.getByRole('button',{name:'Cancel',exact:true}).click();let d=await deck();assert.equal(d.branding.has_project_logo,false);assert.equal(d.project.visibility,'team');assert.deepEqual(d.project.tags,['Original']);
 await page.getByRole('button',{name:'Project settings',exact:true}).click();assert.equal(await form.locator('[name=tags]').count(),0);await modal.getByRole('switch',{name:'Team members only'}).uncheck();
 await page.locator('[data-project-logo-drop]').evaluate((el,data)=>{const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([bytes],'dropped-logo.png',{type:'image/png'}));el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));},png.toString('base64'));
 await page.waitForFunction(()=>document.querySelector('[data-logo-status]')?.textContent.includes('Ready to save'));await modal.getByRole('button',{name:'Save settings',exact:true}).click();await modal.waitFor({state:'hidden'});await page.reload();d=await deck();assert.equal(d.branding.has_project_logo,true);assert.equal(d.project.visibility,'public');assert.deepEqual(d.project.tags,['Original']);assert.equal(d.project.deadline,'2027-01-23');
 // A rejected logo must also roll back the settings sent with it.
 const status=await page.evaluate(async pid=>{const s=await(await fetch('/api.php?action=session')).json(),b=new FormData();b.set('project_id',pid);b.set('visibility','team');b.set('tags','Should not save');b.set('logo',new File(['invalid'],'bad.png',{type:'image/png'}));return(await fetch('/api.php?action=project_settings',{method:'POST',headers:{'X-CSRF-Token':s.csrf},body:b})).status;},made.project_id);assert.equal(status,400);d=await deck();assert.equal(d.project.visibility,'public');assert.deepEqual(d.project.tags,['Original']);assert.equal(d.branding.has_project_logo,true);
 await page.getByRole('button',{name:'Project settings',exact:true}).click();await modal.getByRole('button',{name:'Remove project logo',exact:true}).click();await modal.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await deck()).branding.has_project_logo,true);
 await page.getByRole('button',{name:'Project settings',exact:true}).click();await modal.getByRole('button',{name:'Remove project logo',exact:true}).click();await modal.getByRole('switch',{name:'Team members only'}).check();await modal.getByRole('button',{name:'Save settings',exact:true}).click();await modal.waitFor({state:'hidden'});d=await deck();assert.equal(d.branding.has_project_logo,false);assert.equal(d.project.visibility,'team');assert.equal(d.project.deadline,'2027-01-23');assert.equal(await page.locator('.project-deadline').count(),0);assert.ok(!(await page.locator('.project-sub').innerText()).includes('2027'));
 await page.getByRole('button',{name:'All projects',exact:true}).click();assert.equal(await page.locator('.project-deadline').count(),0);assert.deepEqual(errors,[]);
 await page.setViewportSize({width:390,height:844});await page.locator('.project-tile-open').first().click();await page.getByRole('button',{name:'Project settings',exact:true}).click();const bounds=await modal.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390);await modal.getByRole('button',{name:'Save settings',exact:true}).scrollIntoViewIfNeeded();assert.ok(await modal.getByRole('button',{name:'Save settings',exact:true}).isVisible());
 console.log('PASS Clean settings, visibility switch, tooltip, click/drop logo previews, Cancel, atomic save/removal and preserved hidden deadlines.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
