// Isolated real-app browser check. Google OAuth navigation and API transport are simulated.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const base=process.env.STUDIODECK_TEST_URL,log=process.env.STUDIODECK_TEST_MAIL_LOG,container=process.env.STUDIODECK_TEST_CONTAINER;
if(!base||!log||!container)throw Error('Set STUDIODECK_TEST_URL, STUDIODECK_TEST_MAIL_LOG and STUDIODECK_TEST_CONTAINER to the isolated fake-Google fixture.');
const artifacts=fs.mkdtempSync('/tmp/studiodeck-drive-ui-');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:false,args:['--no-sandbox','--headless=new']});let page;
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.route('https://accounts.google.com/**',async route=>{const u=new URL(route.request().url()),callback=new URL(u.searchParams.get('redirect_uri'));callback.searchParams.set('state',u.searchParams.get('state'));callback.searchParams.set('code','test-code');await route.fulfill({status:302,headers:{location:callback.href},body:''});});
  await page.goto(base);await page.locator('input[name=email]').fill(`drive-ui-${Date.now()}@example.test`);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.locator('.login .notice').waitFor();const token=fs.readFileSync(log,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.reload();const signedIn=page.waitForResponse(r=>r.url().includes('action=consume_login'));await page.locator('[data-form=consume-login] button[type=submit]').click();await signedIn;
  let session=await(await context.request.get(base+'/api.php?action=session')).json();
  if(!session.studio){const r=await context.request.post(base+'/api.php?action=create_studio',{data:{name:'Drive UI test studio'},headers:{'X-CSRF-Token':session.csrf}});assert.equal(r.status(),201);session=await r.json();}
  await page.goto(`${base}/${session.studio.id}/projects`);await page.locator('#project-search').waitFor();
  const api=async(action,data)=>{const r=data===undefined?await context.request.get(base+'/api.php?action='+action):await context.request.post(base+'/api.php?action='+action,{data,headers:{'X-CSRF-Token':session.csrf}});assert.ok(r.ok(),action+': '+await r.text());return r.json();};
  const openUpload=async()=>{await page.locator('[data-action=tab][data-tab=files]').click();await page.locator('[data-action=upload]').first().click();};
  const p=await api('create_project',{name:'Drive browser project',starting_pack:[]});await page.goto(`${base}/${session.studio.id}/projects/${p.project_id}`);await openUpload();await page.getByRole('tab',{name:'From my computer'}).waitFor();assert.equal(await page.getByRole('tab',{name:'From my computer'}).getAttribute('aria-selected'),'true');
  await page.locator('[data-computer-drop]').evaluate(el=>{const d=new DataTransfer();d.items.add(new File(['label,amount\nChair,300\n'],'Chair budget.csv',{type:'text/csv'}));el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:d}));});await page.locator('.upload-selected-list').getByText('Chair budget.csv').waitFor();await page.screenshot({path:path.join(artifacts,'computer-desktop.png')});
  const uploaded=page.waitForResponse(r=>r.url().includes('action=upload')&&r.request().method()==='POST');await page.locator('[data-action=upload-add-local]').click();assert.equal((await uploaded).status(),201);execFileSync('docker',['exec',container,'php','/app/scripts/worker.php','--once']);await page.getByRole('button',{name:'Review files',exact:true}).click();
  await openUpload();await page.getByRole('tab',{name:'From Google Drive'}).click();await page.getByRole('button',{name:'Connect Google Drive',exact:true}).waitFor();await page.screenshot({path:path.join(artifacts,'connect-desktop.png')});await page.getByRole('button',{name:'Connect Google Drive',exact:true}).click();await page.locator('[data-action=drive-open-folder][data-id=villa]').waitFor({timeout:15000});assert.match(await page.locator('.drive-account').innerText(),/drive-owner@example.test/);
  await page.locator('[data-action=drive-open-folder][data-id=villa]').click();await page.locator('[data-drive-file=pdf]').waitFor();assert.equal(await page.locator('[data-action=drive-open-folder] input').count(),0);assert.ok(await page.locator('[data-drive-file=restricted]').isDisabled());await page.locator('[data-drive-file=pdf]').check();await page.getByRole('button',{name:'Load more',exact:true}).click();await page.locator('[data-drive-file=doc]').waitFor();assert.ok(await page.locator('[data-drive-file=pdf]').isChecked());await page.locator('[data-drive-file=doc]').check();await page.screenshot({path:path.join(artifacts,'folder-desktop.png')});
  await page.locator('[data-action=drive-open-folder][data-id=nested]').click();await page.getByText('This folder is empty.',{exact:false}).waitFor();assert.equal(await page.locator('[data-drive-count]').innerText(),'0 selected');await page.locator('[data-action=drive-crumb]').filter({hasText:'Villa documents'}).click();await page.locator('[data-drive-file=pdf]').waitFor();
  await page.locator('[name=folder]').fill('https://drive.google.com/drive/folders/shared');await page.getByRole('button',{name:'Open folder',exact:true}).click();await page.locator('[data-drive-file=shared-pdf]').waitFor();await page.locator('[name=folder]').fill('https://drive.google.com/drive/folders/villa');await page.getByRole('button',{name:'Open folder',exact:true}).click();await page.locator('[data-drive-file=pdf]').waitFor();await page.locator('[data-drive-file=pdf]').check();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'folder-mobile.png')});assert.ok(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
  const imported=page.waitForResponse(r=>r.url().includes('action=drive_import'));await page.locator('[data-action=drive-add]').click();assert.equal((await imported).status(),201);execFileSync('docker',['exec',container,'php','/app/scripts/worker.php','--once']);await page.getByRole('button',{name:'Review files',exact:true}).click();
  let d=await api('project&id='+p.project_id);assert.equal(d.files.length,2);assert.ok(d.files.some(f=>f.metadata.google_drive?.file_id==='pdf'));
  // The same Drive picker can select source files before the project exists.
  await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'All projects',exact:true}).click();await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByRole('button',{name:'Next: project details',exact:true}).click();await page.locator('.modal [name=name]').fill('Created from Drive');await page.getByRole('button',{name:'Next: upload files'}).click();await page.getByRole('button',{name:'From Google Drive',exact:true}).click();await page.locator('[data-action=drive-open-folder][data-id=villa]').waitFor();await page.locator('[data-action=drive-open-folder][data-id=villa]').click();await page.locator('[data-drive-file=pdf]').check();await page.getByRole('button',{name:'Use selected files'}).click();await page.getByRole('button',{name:'Create & process files'}).waitFor();assert.match(await page.locator('.wizard-file-list').innerText(),/Studio terms.pdf/);await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Next: upload files'}).click();assert.match(await page.locator('.wizard-file-list').innerText(),/Studio terms.pdf/);
  const createdImport=page.waitForResponse(r=>r.url().includes('action=drive_import'));await page.getByRole('button',{name:'Create & process files'}).click();assert.equal((await createdImport).status(),201);execFileSync('docker',['exec',container,'php','/app/scripts/worker.php','--once']);await page.waitForFunction(()=>!document.querySelector('#processing-overlay'),{},{timeout:30000});await page.locator('.overview-grid').waitFor();
  const createdPid=new URL(page.url()).pathname.split('/').at(-1);assert.notEqual(createdPid,p.project_id);assert.equal((await api('project&id='+createdPid)).files.length,1);
  await openUpload();await page.getByRole('tab',{name:'From Google Drive'}).click();await page.getByRole('button',{name:'Disconnect',exact:true}).click();await page.getByRole('button',{name:'Connect Google Drive',exact:true}).waitFor();assert.equal((await api('drive_status')).connected,false);assert.deepEqual(errors,[]);
  console.log('PASS desktop/mobile upload tabs, local drag/drop, OAuth popup, folder navigation/link, shared folder, pagination, file-only selection, imports, wizard and disconnect.');console.log('Screenshots: '+artifacts);
 }catch(e){if(page)await page.screenshot({path:path.join(artifacts,'failure.png'),fullPage:true});console.error('Screenshots: '+artifacts);throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
