<?php
declare(strict_types=1);
ob_start();$dir=sys_get_temp_dir().'/studiodeck-source-'.bin2hex(random_bytes(5));mkdir($dir,0700,true);
putenv('DATABASE_PATH='.$dir.'/test.sqlite');putenv('WEBSITE_STORAGE_PATH='.$dir.'/sites');putenv('APP_ENV=local');putenv('APP_URL=http://localhost:8080');putenv('WEBSITE_LOCAL_FREE=false');putenv('STRIPE_PRICE_WEBSITE=price_website');
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/website_public.php';
function check(bool $ok,string $message): void {if(!$ok)throw new RuntimeException($message);echo "PASS $message\n";}
function denied(callable $fn,int $code): void {try{$fn();}catch(RuntimeException $e){check($e->getCode()===$code,'Denied '.$code.': '.$e->getMessage());return;}throw new RuntimeException('Expected denial '.$code);}
try{
 $uid=id();insert('users',['id'=>$uid,'email'=>'website@example.test','name'=>'Studio','created_at'=>now()]);$sid=create_studio($uid,'Studio Willow');$u=['user_id'=>$uid,'studio_id'=>$sid,'email'=>'website@example.test'];$site=website_get($sid);$d=website_with_source(json_decode($site['draft'],true));
 check(!$d['started']&&count(website_templates())===26,'New websites start with the welcome screen and 26 templates');
 check(array_column(website_templates(),'id')[25]==='blank','Blank page is last in the catalog');
 foreach(studio_business_types() as $business){$bold=array_filter(website_templates(),fn($t)=>in_array($business['id'],$t['business_types'],true)&&in_array('experimental',$t['styles'],true));check(count($bold)===3,'Three experimental designs for '.$business['id']);}
 $blank=website_seed_files($d,'blank');check(!str_contains($blank['index.html'],'class="hero"')&&$blank['script.js']==='','Blank template contains no predefined sections');
 foreach(website_templates() as $t){$files=website_seed_files($d,$t['id']);check(!website_source_checks($sid,$files)['errors'],'Template '.$t['id'].' is a valid standalone page');}
 $site=website_start($u,['template'=>'noir','revision'=>1]);$d=json_decode($site['draft'],true);check($d['started']&&isset($d['files']['script.js']),'Choosing a template saves editable source and an owned hero image');
 $d['files']['index.html']=str_replace('Spaces made for living.','A completely personal website',$d['files']['index.html']);$d['files']['styles.css'].="\n.my-custom-grid { display: grid; grid-template-columns: 1fr 2fr; }";$d['files']['script.js']='document.body.dataset.interactive = "yes";';$site=website_save($u,$d,2);
 $image=imagecreatetruecolor(1800,1200);imagefill($image,0,0,imagecolorallocate($image,150,130,100));ob_start();imagepng($image);$bytes=ob_get_clean();imagedestroy($image);
 $pid=id();$iid=id();$aid=id();$vid=id();$slide=id();insert('projects',['id'=>$pid,'studio_id'=>$sid,'user_id'=>$uid,'name'=>'Miller family','description'=>'Private budget discussion','created_at'=>now()]);insert('project_members',['project_id'=>$pid,'user_id'=>$uid]);insert('iterations',['id'=>$iid,'project_id'=>$pid,'number'=>1,'title'=>'First','created_at'=>now()]);insert('assets',['id'=>$aid,'project_id'=>$pid,'category'=>'renders','created_at'=>now()]);insert('file_versions',['id'=>$vid,'asset_id'=>$aid,'number'=>1,'name'=>'original.png','mime'=>'image/png','size'=>strlen($bytes),'sha256'=>hash('sha256',$bytes),'data'=>$bytes,'created_at'=>now()]);insert('presentation_slides',['id'=>$slide,'iteration_id'=>$iid,'source_version_id'=>$vid,'type'=>'photo','title'=>'Living room','position'=>0]);
 $seen=[];$proposal=website_chat_edit($u,['prompt'=>'Add the Miller family project','revision'=>3],function($system,$content)use(&$seen,$pid){$seen=json_decode($content[0]['text'],true);return ['project_id'=>$pid,'message'=>'Review the public text and images first.'];});
 check($proposal['project_id']===$pid&&!str_contains(json_encode($seen),'Private budget discussion')&&(int)website_get($sid)['revision']===3,'Chat finds authorized projects without exposing private descriptions or saving unreviewed work');
 $site=website_import($u,['project_id'=>$pid,'revision'=>3,'title'=>'Miller <script>bad()</script>','description'=>'A calm family home.','images'=>[['id'=>$slide,'alt'=>'Sunlit living room with oak furniture']]]);$d=json_decode($site['draft'],true);$public=$d['projects'][0]['id'];$asset=$d['projects'][0]['images'][0]['asset'];
 check(str_contains($d['files']['index.html'],'A completely personal website')&&str_contains($d['files']['styles.css'],'.my-custom-grid')&&$d['files']['script.js']==='document.body.dataset.interactive = "yes";','Adding reviewed project content preserves unrelated custom HTML, CSS and JS');
 check(str_contains($d['files']['index.html'],'&lt;script&gt;')&&!str_contains($d['files']['index.html'],'<script>bad()'),'Imported public content is escaped');
 $missing=$d;unset($missing['files']);denied(fn()=>website_save($u,$missing,4),409);
 $whitespace=website_source_replace_result(['index.html'=>'<html><body>ok</body></html>','styles.css'=>"a {\n color: red;\n}\n",'script.js'=>''],['patches'=>[['file'=>'styles.css','find'=>" color: red;\n",'replace'=>" color: blue;\n"]]]);check($whitespace['styles.css']==="a {\n color: blue;\n}\n",'Exact code edits preserve meaningful whitespace');
 $before=$d['files'];$answer=website_chat_edit($u,['prompt'=>'Our new address is Oak Street 12. Add it to contact.','revision'=>4],fn()=>['patches'=>[['file'=>'index.html','find'=>'<section class="contact" id="contact">','replace'=>'<section class="contact" id="contact"><address>Oak Street 12</address>']],'message'=>'Added the new address to contact.']);
 check(str_contains($answer['website']['draft']['files']['index.html'],'Oak Street 12')&&$answer['website']['draft']['files']['styles.css']===$before['styles.css'],'Chat edits actual source while preserving unrelated files');
 denied(fn()=>website_chat_edit($u,['prompt'=>'Invalid patch','revision'=>5],fn()=>['patches'=>[['file'=>'styles.css','find'=>'NOT PRESENT','replace'=>'oops']],'message'=>'Changed']),409);
 check((int)website_get($sid)['revision']===5,'A failed exact patch leaves the entire draft unchanged');
 $bad=$answer['website']['draft']['files'];$bad['index.html']=str_replace('</body>','<a href="projects/new.html">New page</a></body>',$bad['index.html']);check((bool)website_source_checks($sid,$bad)['errors'],'Multi-page links are rejected');
 denied(fn()=>website_publish($u,5),402);putenv('WEBSITE_LOCAL_FREE=true');check(website_billing_status(website_get($sid))['active'],'Local mode enables publishing');putenv('APP_ENV=production');check(!website_billing_status(website_get($sid))['active'],'Production ignores local bypass');putenv('APP_ENV=local');
 $r=website_publish($u,5);$root=website_dir($sid).'/releases/'.$r['id'].'/public';$html=file_get_contents($root.'/index.html');check(is_file($root.'/styles.css')&&is_file($root.'/script.js')&&!is_dir($root.'/projects'),'Publication exports one page and ordinary CSS/JS files');check(str_contains($html,'Oak Street 12')&&str_contains($html,'application/ld+json')&&str_contains($html,'og:image'),'Source changes and automatic SEO survive publication');check(str_contains($html,'srcset=')&&count(glob($root.'/assets/*-1600.webp'))>0,'Referenced images receive responsive compressed variants');
 $snapshot=file_get_contents(website_dir($sid).'/current.json');transaction(fn()=>delete_project_records($pid));check(file_get_contents($root.'/index.html')===$html,'Source project deletion cannot alter the static website');
 $d=$answer['website']['draft'];$d['files']['styles.css'].="\n/* another custom edit */";website_save($u,$d,5);check(file_get_contents(website_dir($sid).'/current.json')===$snapshot,'Draft source edits never change the live release');denied(fn()=>website_publish($u,5),409);
 $d['files']=$bad;website_save($u,$d,6);denied(fn()=>website_publish($u,7),400);check(file_get_contents(website_dir($sid).'/current.json')===$snapshot,'Invalid source cannot replace the working live version');
 $_SERVER['HTTP_HOST']='localhost:8080';ob_start();website_public_route('/sites/'.$sid.'/');$out=ob_get_clean();check($out===$html,'Public route serves the independent static page');ob_start();website_public_route('/sites/'.$sid.'/script.js');$script=ob_get_clean();check(str_contains($script,'interactive'),'Public route serves vanilla JavaScript');
 $policy=website_code_policy();check(str_contains($policy,'sandbox allow-scripts')&&!str_contains($policy,'allow-same-origin')&&str_contains($policy,"connect-src 'none'"),'Generated code is isolated from authenticated app state');
 $uid2=id();insert('users',['id'=>$uid2,'email'=>'other@example.test','name'=>'Other','created_at'=>now()]);$sid2=create_studio($uid2,'Other');website_get($sid2);check((bool)website_source_checks($sid2,$before)['errors'],'Foreign website assets cannot be referenced');
 $keep=id();insert('projects',['id'=>$keep,'studio_id'=>$sid,'user_id'=>$uid,'name'=>'Keep original project','created_at'=>now()]);
 query("UPDATE websites SET subscription_id='sub_reset_test',subscription_status='active',paid_until=1234567890,domain='www.reset.example',domain_verified=1 WHERE studio_id=?",[$sid]);
 website_write(website_dir($sid).'/domain.json',json_encode(['name'=>'www.reset.example','studio_id'=>$sid]));
 $settings=website_get($sid);$usage=rows('SELECT * FROM website_ai_usage WHERE studio_id=?',[$sid]);
 denied(fn()=>website_reset($u,6),409);check(file_get_contents(website_dir($sid).'/current.json')===$snapshot,'Stale reset preserves the live website');
 query("CREATE TRIGGER reject_test_reset BEFORE UPDATE ON websites BEGIN SELECT RAISE(ABORT,'Test reset failure'); END");
 $failed=false;try{website_reset($u,7);}catch(Throwable $e){$failed=true;}query('DROP TRIGGER reject_test_reset');
 check($failed&&file_get_contents($root.'/index.html')===$html&&file_get_contents(website_dir($sid).'/current.json')===$snapshot&&one('SELECT 1 FROM website_assets WHERE id=?',[$asset]),'Failed reset rolls back files and database together');
 website_reset($u,7);$fresh=website_payload($u);$saved=website_get($sid);
 check(!$fresh['draft']['started']&&!$fresh['draft']['projects']&&!$fresh['draft']['testimonials']&&!$fresh['draft']['conversation']&&!$fresh['live']&&!$fresh['releases']&&!$fresh['can_undo']&&$fresh['revision']===8,'Reset clears website content and returns to the welcome screen');
 check(!one('SELECT 1 FROM website_assets WHERE studio_id=?',[$sid])&&!is_dir(website_dir($sid).'/releases')&&!glob(website_dir($sid).'/.reset-*'),'Reset removes original website images and published files');
 check(one('SELECT 1 FROM projects WHERE id=?',[$keep])&&website_get($sid2)['revision']===1,'Reset preserves source projects and other studios');
 foreach(['subscription_id','subscription_status','paid_until','domain','domain_token','domain_verified'] as $key)check($saved[$key]===$settings[$key],'Reset preserves '.$key);
 check(rows('SELECT * FROM website_ai_usage WHERE studio_id=?',[$sid])===$usage&&is_file(website_dir($sid).'/domain.json'),'Reset retains usage limits and verified domain setup');
 ob_start();website_public_route('/sites/'.$sid.'/');$removed=ob_get_clean();check(http_response_code()===404&&$removed==='Website unavailable.','Removed website is no longer served');
 website_start($u,['template'=>'coast','revision'=>8]);check(website_payload($u)['draft']['started'],'A new starting design can be chosen after reset');
 echo "Website source checks passed.\n";
}finally{website_remove_build($dir);}
