import assert from 'node:assert/strict';
import {projectThemeVariables} from '../public/assets/project-theme.js';
import {studioPalettes} from '../public/assets/studio.js';
assert.equal(Object.keys(studioPalettes).length,14);
const light=projectThemeVariables({colors:['#172838','#eeeecc'],font:'serif'});
const dark=projectThemeVariables({colors:['#172838','#eeeecc'],font:'sans',mode:'dark',background:'#152235'});
assert.equal(dark['--deck-bg'],'#152235');assert.equal(dark['--ink'],'#f5f5f2');assert.equal(dark['--heading'],'Arial,sans-serif');
assert.equal(projectThemeVariables({mode:'dark',background:'#111314'})['--deck-bg'],'#111314');
assert.notEqual(light['--deck-bg'],dark['--deck-bg']);
assert.equal(projectThemeVariables({colors:['invalid'],mode:'dark',background:'invalid'})['--deck-bg'],'#152235');
console.log('PASS Fourteen studio palettes and independent, readable light/dark project themes.');
assert.equal(projectThemeVariables({mode:'light',light_background:'#f6f0e5',background:'#111314'})['--deck-bg'],'#f6f0e5');
assert.equal(projectThemeVariables({mode:'dark',light_background:'#f6f0e5',background:'#253128'})['--deck-bg'],'#253128');
assert.equal(projectThemeVariables({mode:'light',light_background:'invalid'})['--deck-bg'],projectThemeVariables({mode:'light'})['--deck-bg']);
console.log('PASS Light and dark background choices remain independent, with safe legacy defaults.');
const {cleanStudioTheme,studioThemeVariables}=await import('../public/assets/studio.js');
assert.deepEqual(cleanStudioTheme({palette:'ocean',style:'modern',font:'sans'}),{palette:'warmgray',style:'editorial',font:'sans'});
assert.equal(cleanStudioTheme({font:'invalid'}).font,'serif');
assert.equal(cleanStudioTheme(null).font,'serif');
assert.ok(studioThemeVariables({font:'sans'})['--heading'].includes('DM Sans'));
assert.equal(studioThemeVariables()['--green'],'#55534f');
assert.ok(studioThemeVariables()['--heading'].includes('Georgia'));
console.log('PASS Workspace keeps warm grayscale and supports independent serif or DM Sans headings.');
