// Run with an isolated server and log-only email, as with test_budget_controls.cjs.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict');
const base=process.env.STUDIODECK_TEST_URL,mailLog=process.env.STUDIODECK_TEST_MAIL_LOG;
if(!base||!mailLog)throw Error('Set STUDIODECK_TEST_URL and STUDIODECK_TEST_MAIL_LOG for an isolated fixture.');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:false,args:['--no-sandbox','--headless=new']});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('input[name=email]').fill(`question-${Date.now()}@example.test`);await page.getByRole('button',{name:'Email me a sign-in link'}).click();await page.waitForSelector('.login .notice');const token=fs.readFileSync(mailLog,'utf8').trim().split('\n').at(-1).split('/#/login/')[1];await page.goto(base+'/#/login/'+token);await page.reload();await page.getByRole('button',{name:'Open my studio'}).click();await page.waitForSelector('#project-search');
const made=await page.evaluate(async()=>{const s=await(await fetch('/api.php?action=session')).json();const p=await(await fetch('/api.php?action=create_project',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:JSON.stringify({name:'Question log test'})})).json();return {...p,studio:s.studio.id};});
const slideUrl=`${base}/${made.studio}/slide/budget?project=${made.project_id}&iteration=${made.iteration_id}`;await page.goto(slideUrl);await page.locator('.presentation-budget').waitFor();
const question='What is the total budget? <img src=x onerror=alert(1)>';
await page.getByRole('textbox',{name:'Ask about costs and scope'}).fill(question);const response=page.waitForResponse(r=>r.url().includes('action=budget_chat'));await page.getByRole('button',{name:'Send question',exact:true}).click();const answer=await(await response).json();await page.locator('.chat-message.assistant').waitFor();assert.equal(answer.activity_event.question_answer.slide,'budget');
await page.getByRole('button',{name:'Back to studio',exact:true}).click();await page.locator('[data-action=tab][data-tab=activity]').click();const entry=page.locator('.activity-question-answer');await entry.waitFor();assert.ok((await entry.innerText()).includes(question));assert.ok((await entry.innerText()).includes(answer.answer));assert.equal(await entry.locator('img').count(),0);const href=await entry.locator('a').getAttribute('href');assert.ok(href.includes('/slide/budget'));assert.ok(href.includes('iteration='+made.iteration_id));assert.ok(href.includes('project='+made.project_id));await page.reload();await entry.waitFor();
await page.locator('.sidebar [data-action=all-activity]').click();await entry.waitFor();assert.ok((await entry.innerText()).includes(answer.answer));await entry.locator('a').click();await page.locator('.presentation-budget').waitFor();assert.equal(new URL(page.url()).searchParams.get('iteration'),made.iteration_id);await page.reload();await page.locator('.presentation-budget').waitFor();assert.deepEqual(errors,[]);console.log('PASS question/answer in both activity views, safe text rendering, persisted exact slide link and reload.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
