import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../public/assets/app.js',import.meta.url),'utf8');
const code=source.slice(source.indexOf('async function api('),source.indexOf('\nfunction toast('));
const logs=[];
const context=vm.createContext({TOUR_MODE:false,DEMO:false,state:{csrf:'private-token',client:false},getActions:new Set(),accountActions:new Set(),URLSearchParams,FormData,resourceHeaders:()=>({}),console:{error:(...v)=>logs.push(v)},tr:v=>v,translateError:v=>v});
vm.runInContext(code,context);
context.fetch=async()=>({ok:false,status:500,json:async()=>({error:'Something went wrong.',debug:{exception:'PDOException',message:'no such column: customer_parameters'}})});
await assert.rejects(()=>context.api('billing_checkout',{secret:'do-not-log'}),error=>error.status===500&&/Something went wrong/.test(error.message));
assert.equal(logs[0][1].details.message,'no such column: customer_parameters');
assert.equal(logs[0][1].action,'billing_checkout');
assert(!JSON.stringify(logs).includes('private-token'));assert(!JSON.stringify(logs).includes('do-not-log'));
context.fetch=async()=>{throw Error('Failed to fetch');};
await assert.rejects(()=>context.api('billing_checkout'),/Failed to fetch/);
assert.equal(logs[1][0],'[Studiodeck API] Network request failed');
context.fetch=async()=>({status:502,headers:new Map([['content-type','text/html']]),json:async()=>{throw Error('Invalid JSON');}});
await assert.rejects(()=>context.api('billing_checkout'));
assert.equal(logs[2][0],'[Studiodeck API] Invalid JSON response');
console.log('PASS API errors log technical, network and JSON diagnostics without request bodies or credentials.');
