// Isolated browser review using the fixture exported by test_consistency.py.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),fixture=JSON.parse(fs.readFileSync(process.env.CONSISTENCY_BROWSER_EXPORT,'utf8'));
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));
  fixture.session.studio.setup_completed_at=new Date().toISOString();
  const deck=fixture.deck;deck.jobs=[];deck.checks.available=true;
  await page.route('**/*',async route=>{
   const url=new URL(route.request().url());
   if(url.pathname==='/api.php'){
    const action=url.searchParams.get('action'),body=route.request().postDataJSON()||{};requests.push({action,body});let value={ok:true};
    if(action==='session')value=fixture.session;
    if(action==='project'||action==='deck')value=deck;
    if(action==='projects')value={projects:[]};
    if(action==='comments_feed')value={items:[],has_more:false,unread_count:0};
    if(action==='project_access')value={reason:'ready'};
    if(action==='run_consistency_checks')deck.jobs=[{id:'scan-1',type:'consistency',status:'queued'}];
    if(action==='review_consistency_finding'){
     const finding=deck.checks.findings.find(f=>f.id===body.id);
     if(body.operation==='question'){
      finding.question_id='prepared-question';
      const q={id:finding.question_id,iteration_id:deck.iteration.id,question:finding.question,reason:finding.explanation,thread_id:'prepared-thread',accepted:1,published:0,resolved:0,dismissed:0,item_type:'question',replies:[],citations:[]};
      deck.open_questions=[q];deck.communication.items=[q];
      const c={...deck.communication.comments[0],id:q.thread_id,slide:'general',body:finding.question+'\n\n'+finding.explanation,audience:'studio',created_at:new Date().toISOString(),thread_details:{type:'conversation',question_id:q.id},is_open:true};
      deck.communication.comments.push(c);deck.comments.push(c);deck.communication.threads.push({id:c.id,title:finding.question});
      value={ok:true,question_id:q.id};
     }else finding.status=body.operation;
    }
    if(action==='check_source_role'){deck.checks.roles[body.source_key]=body.role;deck.checks.run.stale=true;}
    if(action==='check_image')return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5AAAAABJRU5ErkJggg==','base64')});
    if(['file','slide_image','studio_logo','project_cover'].includes(action))return route.fulfill({status:404,body:''});
    return route.fulfill({contentType:'application/json',body:JSON.stringify(value)});
   }
   if(url.pathname.startsWith('/assets/')||url.pathname.startsWith('/auth/')){const file=path.join(root,'public',url.pathname);return route.fulfill({contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'image/svg+xml',body:fs.readFileSync(file)});}
   return route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(root,'public/index.html'))});
  });
  await page.goto('http://checks.test/studio-a/projects/shared?tab=checks&iteration=iteration-shared');
  const scanButton=page.getByRole('button',{name:'Suggest items',exact:true});
  await scanButton.waitFor();
  assert.equal(await page.locator('.comm-suggestions,.consistency-panel').count(),0);
  await scanButton.click();
  assert.equal(requests.filter(r=>r.action==='run_consistency_checks').length,0);
  assert.doesNotMatch(await page.locator('.modal').textContent(),/How the scan works|Findings to review|Last checked|Some evidence could not be checked/);
  assert.equal(await page.locator('.modal .check-finding').count(),1);
  assert.equal(await page.locator('.check-question-preview p').innerText(),deck.checks.findings[0].question);
  assert(await page.locator('[data-action=check-start]').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));
  await page.locator('.check-finding-sources>summary').click();
  assert.match(await page.locator('.check-finding').innerText(),/Written requirement/);
  await page.locator('[data-action=check-evidence][data-evidence="1"]').click();
  await page.locator('.check-region').waitFor();
  assert.equal(await page.locator('.check-image img').count(),1);
  await page.keyboard.press('Escape');
  await scanButton.click();
  await page.getByRole('button',{name:'Create conversation',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('.modal'));
  await page.locator('.comm-thread').getByText(deck.checks.findings[0].question,{exact:false}).first().waitFor();
  assert(requests.some(r=>r.action==='review_consistency_finding'&&r.body.operation==='question'));
  await scanButton.click();
  await page.getByRole('button',{name:'Open conversation',exact:true}).waitFor();
  await page.getByRole('button',{name:'Hide as irrelevant',exact:true}).last().click();
  await page.locator('.modal [data-check-details=reviewed]').waitFor();
  assert.equal(await page.locator('.modal .check-finding:visible').count(),0);
  await page.keyboard.press('Escape');
  await scanButton.click();
  assert.equal(await page.locator('.modal .check-finding:visible').count(),0);
  await page.locator('.modal [data-check-details=reviewed]>summary').click();
  await page.locator('.modal [data-operation=open]').click();
  await page.locator('.modal [data-operation=dismissed]').waitFor();
  await page.keyboard.press('Escape');
  await page.locator('[data-action=tab][data-tab=files]').click();
  await page.locator('.check-sources>summary').click();
  await page.locator('[data-action=check-role][data-key="file-shared:p:0"]').click();
  await page.locator('[name=role]').selectOption('inspiration');
  await page.locator('[data-form=check-role] [type=submit]').click();
  await page.locator('[data-action=tab][data-tab=comments]').click();
  await scanButton.click();
  assert(requests.some(r=>r.action==='check_source_role'&&r.body.role==='inspiration'));
  await page.locator('[data-action=check-start]').click();
  await page.waitForFunction(()=>!document.querySelector('.modal'));
  await page.waitForFunction(()=>document.querySelector('[data-action=check-run].is-scanning'));
  assert(requests.some(r=>r.action==='run_consistency_checks'));
  assert.equal(await scanButton.isEnabled(),true);
  assert.equal(await scanButton.locator('svg').evaluate(el=>getComputedStyle(el).animationName),'check-star-pulse');
  await scanButton.click();
  await page.getByText('Scan queued…',{exact:true}).last().waitFor();
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await scanButton.locator('svg').evaluate(el=>getComputedStyle(el).animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  assert.equal(await page.locator('[data-action=check-start]').isDisabled(),true);
  assert.equal(await page.locator('.modal .check-finding').count(),1);
  deck.jobs[0].status='running';deck.jobs[0].progress={stage:'comparing_sources'};
  await page.locator('.modal').getByText('Comparing specifications and images',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Continue working',exact:true}).click();
  await page.locator('[data-action=tab][data-tab=files]').click();
  await page.locator('#file-search').fill('draft search');
  deck.jobs[0].progress={stage:'verifying_mismatch'};
  const reads=requests.filter(r=>r.action==='project').length;
  await page.waitForFunction(()=>document.querySelector('#file-search')===document.activeElement);
  await page.waitForTimeout(2100);
  assert(requests.filter(r=>r.action==='project').length>reads);
  assert.equal(await page.locator('#file-search').inputValue(),'draft search');
  assert.equal(await page.locator('#file-search').evaluate(el=>el===document.activeElement),true);
  await page.locator('[data-action=tab][data-tab=comments]').click();
  await scanButton.click();
  deck.jobs[0].status='done';deck.checks.run.stale=false;deck.checks.run.checked_at=new Date().toISOString();
  deck.checks.findings.push({...deck.checks.findings[0],id:'new-finding',title:'Another inconsistency found',stale:false});
  await page.locator('.modal').getByText('Another inconsistency found',{exact:true}).waitFor();
  assert.equal(await page.locator('[data-action=check-start]').isEnabled(),true);
  assert.equal(await scanButton.evaluate(el=>el.classList.contains('is-scanning')),false);
  assert.equal(requests.filter(r=>r.action==='run_consistency_checks').length,1);
  await page.screenshot({path:'/tmp/studiodeck-consistency-desktop.png',fullPage:false});
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=1);
  assert(await page.locator('.modal .consistency-panel').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await page.screenshot({path:process.env.CONSISTENCY_SCREENSHOT||'/tmp/studiodeck-consistency-mobile.png',fullPage:false});
  assert(await page.locator('.modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:1440,height:1000});
  await scanButton.click();
  await page.locator('[data-action=check-start]').click();
  await scanButton.click();
  deck.jobs[0].status='failed';
  await page.locator('.modal').getByText(/The scan could not finish/).waitFor();
  assert.equal(await page.locator('.modal .check-finding').count(),2);
  assert.equal(await page.locator('[data-action=check-start]').isEnabled(),true);
  assert.equal(await scanButton.evaluate(el=>el.classList.contains('is-scanning')),false);
  // A scan queued elsewhere is also visible after reopening the project.
  deck.jobs=[{id:'scan-2',type:'consistency',status:'running',progress:{stage:'checking_sources'}}];
  await page.reload();
  await page.locator('[data-action=check-run].is-scanning').first().waitFor();
  await scanButton.click();
  await page.locator('.modal').getByText('Classifying sources and reading design details',{exact:true}).waitFor();
  deck.jobs[0].status='done';deck.checks.findings=[];deck.checks.run.warnings=['Only some files could be read.'];
  await page.getByText('No suggestions this time',{exact:true}).waitFor();
  assert.equal(await page.locator('.check-empty-art').count(),1);
  assert.doesNotMatch(await page.locator('.modal').textContent(),/How the scan works|Findings to review|Last checked|Some evidence could not be checked|Only some files/);
  await page.screenshot({path:'/tmp/studiodeck-suggestions-empty.png'});
  await page.setViewportSize({width:390,height:844});
  assert(await page.locator('.modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  assert.deepEqual(errors,[]);
  console.log('PASS Communication suggestions, clean popup, illustrated empty state, prepared conversations, hide/restore, background scanning, animated progress, live results, preserved typing, evidence, roles and mobile layout.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
