CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS login_tokens (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits (key_hash TEXT PRIMARY KEY, hits INTEGER NOT NULL, reset_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), name TEXT NOT NULL, location TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', theme TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);
CREATE TABLE IF NOT EXISTS contacts (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), name TEXT NOT NULL, role TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS idx_contacts_project ON contacts(project_id);
CREATE TABLE IF NOT EXISTS iterations (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), number INTEGER NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', theme TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, UNIQUE(project_id, number));
CREATE TABLE IF NOT EXISTS assets (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), category TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_assets_project ON assets(project_id);
CREATE TABLE IF NOT EXISTS file_versions (id TEXT PRIMARY KEY, asset_id TEXT NOT NULL REFERENCES assets(id), parent_id TEXT REFERENCES file_versions(id), number INTEGER NOT NULL, name TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, sha256 TEXT NOT NULL, data BLOB NOT NULL, preview BLOB, extracted_text TEXT NOT NULL DEFAULT '', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, UNIQUE(asset_id, number));
CREATE TABLE IF NOT EXISTS iteration_files (iteration_id TEXT NOT NULL REFERENCES iterations(id), asset_id TEXT NOT NULL REFERENCES assets(id), version_id TEXT NOT NULL REFERENCES file_versions(id), category TEXT NOT NULL, PRIMARY KEY(iteration_id,asset_id));
CREATE TABLE IF NOT EXISTS budget_items (id TEXT PRIMARY KEY, iteration_id TEXT NOT NULL REFERENCES iterations(id), parent_id TEXT REFERENCES budget_items(id), source_version_id TEXT REFERENCES file_versions(id), label TEXT NOT NULL, vendor TEXT NOT NULL DEFAULT '', amount_cents INTEGER, kind TEXT NOT NULL DEFAULT 'estimate', included INTEGER NOT NULL DEFAULT 0, note TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS idx_budget_iteration ON budget_items(iteration_id);
CREATE TABLE IF NOT EXISTS shares (id TEXT PRIMARY KEY, iteration_id TEXT NOT NULL REFERENCES iterations(id), token_hash TEXT NOT NULL UNIQUE, email TEXT NOT NULL, expires_at INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_shares_iteration ON shares(iteration_id);
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, iteration_id TEXT NOT NULL REFERENCES iterations(id), slide TEXT NOT NULL, author TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_comments_iteration ON comments(iteration_id);
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), iteration_id TEXT, actor TEXT NOT NULL, type TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_events_project_time ON events(project_id,created_at);
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), iteration_id TEXT NOT NULL REFERENCES iterations(id), version_id TEXT REFERENCES file_versions(id), type TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'queued', error TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, started_at TEXT);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status,created_at);
CREATE TABLE IF NOT EXISTS document_pages (version_id TEXT NOT NULL REFERENCES file_versions(id), number INTEGER NOT NULL, text TEXT NOT NULL, metadata TEXT NOT NULL, preview BLOB, PRIMARY KEY(version_id,number));
CREATE TABLE IF NOT EXISTS document_images (version_id TEXT NOT NULL, page_number INTEGER NOT NULL, number INTEGER NOT NULL, metadata TEXT NOT NULL, data BLOB NOT NULL, PRIMARY KEY(version_id,page_number,number), FOREIGN KEY(version_id,page_number) REFERENCES document_pages(version_id,number) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS slide_image_versions (id TEXT PRIMARY KEY, parent_id TEXT REFERENCES slide_image_versions(id), source_version_id TEXT NOT NULL REFERENCES file_versions(id), mime TEXT NOT NULL, data BLOB NOT NULL, metadata TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS presentation_slides (id TEXT NOT NULL, iteration_id TEXT NOT NULL REFERENCES iterations(id), source_version_id TEXT NOT NULL REFERENCES file_versions(id), page_number INTEGER NOT NULL DEFAULT 0, image_number INTEGER NOT NULL DEFAULT 0, type TEXT NOT NULL, situation TEXT NOT NULL DEFAULT 'unknown', title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', metadata TEXT NOT NULL DEFAULT '{}', position INTEGER NOT NULL, image_version_id TEXT REFERENCES slide_image_versions(id), PRIMARY KEY(iteration_id,id), UNIQUE(iteration_id,source_version_id,page_number,image_number));
CREATE INDEX IF NOT EXISTS idx_slides_source ON presentation_slides(iteration_id,source_version_id);
CREATE TABLE IF NOT EXISTS slide_layout (iteration_id TEXT NOT NULL REFERENCES iterations(id), slide_id TEXT NOT NULL, hidden INTEGER NOT NULL DEFAULT 0, deleted INTEGER NOT NULL DEFAULT 0, position INTEGER, PRIMARY KEY(iteration_id,slide_id));
CREATE TABLE IF NOT EXISTS studio_preferences (user_id TEXT PRIMARY KEY REFERENCES users(id), theme TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS studios (id TEXT PRIMARY KEY,name TEXT NOT NULL,theme TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS studio_members (studio_id TEXT NOT NULL REFERENCES studios(id),user_id TEXT NOT NULL REFERENCES users(id),display_name TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT 'member' CHECK(role IN ('admin','member')),PRIMARY KEY(studio_id,user_id));
CREATE TABLE IF NOT EXISTS project_members (project_id TEXT NOT NULL REFERENCES projects(id),user_id TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(project_id,user_id));
CREATE TABLE IF NOT EXISTS project_pins (project_id TEXT NOT NULL REFERENCES projects(id),user_id TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(project_id,user_id));
CREATE TABLE IF NOT EXISTS studio_logos (studio_id TEXT PRIMARY KEY REFERENCES studios(id),data BLOB NOT NULL,mime TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS person_profiles (person_key TEXT PRIMARY KEY,name TEXT NOT NULL DEFAULT '',color TEXT NOT NULL DEFAULT '',avatar BLOB,email_comments INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS comment_reads (comment_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,person_key TEXT NOT NULL,read_at TEXT NOT NULL,PRIMARY KEY(comment_id,person_key));
CREATE TABLE IF NOT EXISTS project_logos (project_id TEXT PRIMARY KEY REFERENCES projects(id),data BLOB NOT NULL,mime TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS share_aliases (token_hash TEXT PRIMARY KEY,share_id TEXT NOT NULL REFERENCES shares(id));
CREATE TABLE IF NOT EXISTS email_outbox (id TEXT PRIMARY KEY,comment_id TEXT NOT NULL REFERENCES comments(id),person_key TEXT NOT NULL,email TEXT NOT NULL,user_id TEXT,share_id TEXT,url TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',attempts INTEGER NOT NULL DEFAULT 0,next_attempt INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',UNIQUE(comment_id,email));
CREATE TABLE IF NOT EXISTS project_details (project_id TEXT PRIMARY KEY REFERENCES projects(id),tags TEXT NOT NULL DEFAULT '[]',deadline TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS slide_sections (iteration_id TEXT NOT NULL REFERENCES iterations(id),slide_id TEXT NOT NULL,section TEXT NOT NULL,PRIMARY KEY(iteration_id,slide_id));

CREATE TABLE IF NOT EXISTS slide_groups (iteration_id TEXT NOT NULL REFERENCES iterations(id),id TEXT NOT NULL,label TEXT NOT NULL,position INTEGER NOT NULL,PRIMARY KEY(iteration_id,id));
CREATE TABLE IF NOT EXISTS project_delete_confirmations (token_hash TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id),expires_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS budget_choices (budget_item_id TEXT PRIMARY KEY REFERENCES budget_items(id) ON DELETE CASCADE, selected INTEGER NOT NULL DEFAULT 0, range_percent INTEGER NOT NULL DEFAULT 0 CHECK(range_percent BETWEEN 0 AND 100), updated_by TEXT NOT NULL, updated_at TEXT NOT NULL);
