"""Build Haus Morgenlicht: an original fictional Austrian chalet conversion.

Images are generated separately with the built-in image_gen tool, including
matched before/proposed edits and a season edit of the same chalet.
"""
from pathlib import Path
from html import escape as e
import csv
import json
from demo_visual_studies import add_visual_studies

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'demos/haus-morgenlicht'
OUT.mkdir(parents=True,exist_ok=True)
(OUT/'assets').mkdir(exist_ok=True)
(OUT/'suppliers').mkdir(exist_ok=True)
def money(v):return '€'+f'{v:,.0f}'
def row(key,label,vendor,amount,source,parent='',included=False,kind='quote',low=None,high=None,optional=False,note=''):
    return dict(key=key,label=label,vendor=vendor+' — fictional',amount=amount,source=source,parent=parent,included=included,kind=kind,min_amount=low,max_amount=high,optional=optional,note=note)
budget=[
 row('build','Conversion construction package','Alpen Bauatelier',248000,'AB-260918',note='€92,000 structure/replanning + €98,000 roof/fabric + €58,000 building services. Subquotes included once.'),
 row('structure','Structural adaptations & replanning','Berg Struktur',92000,'BS-260918','build',True,note='Included in Alpen Bauatelier. Local openings, supports, selective partitions and making good; technical design required.'),
 row('roof','Roof renewal & envelope insulation','Dach & Holz',98000,'DH-260918','build',True,note='Included in main construction. Preserve roof geometry; renewed weathering layers and insulation allowance. Glazing separately priced.'),
 row('services','Building services coordination','Haus Technik',58000,'HT-260918','build',True,note='Included in construction: €24,000 electrical + €34,000 heating/ventilation. Decorative light fixtures excluded.'),
 row('electrical','Electrical installation & controls','Lichtwerk Tirol',24000,'LT-260918','services',True,note='Second-tier included subquote within Haus Technik and Alpen Bauatelier. Do not add again.'),
 row('heating','Heating & ventilation package','Klima Berg',34000,'KB-260918','services',True,note='Included in Haus Technik. System selection and performance follow specialist design; no energy rating is promised.'),
 row('glazing','Windows, doors & enlarged view openings','Panorama Werk',104000,'PW-260918',note='€64,000 glazing supply + €40,000 frames, installation and detailing. Structural opening work is in Berg Struktur.'),
 row('glass','Glazing fabrication package','Alpenglas',64000,'AG-260918','glazing',True,note='Included in Panorama Werk. Fabrication allowance pending thermal, structural and safety specifications.'),
 row('joinery','Kitchen & bespoke silver-fir joinery','Fir Atelier',78000,'FA-260918',note='€62,000 cabinetry, worktops and fitting + €16,000 appliances. Includes arrival storage and selected bedroom joinery.'),
 row('appliances','Integrated kitchen appliances','Kochraum',16000,'KR-260918','joinery',True,note='Included in Fir Atelier; final equipment schedule to be selected.'),
 row('finishes','Timber floors, plaster & stone finishes','Stein & Faser',42000,'SF-260918',note='General interior floor and wall finishes. Kitchen worktops and bathroom vanity are in their own packages.'),
 row('furniture','Furniture, curtains & textiles','Hochraum Editions',None,'HE-260918',kind='estimate',low=42000,high=58000,note='Base selection €42,000; premium upholstery, rugs and loose furniture €58,000. Terrace option separate.'),
 row('lighting','Decorative lighting','Lumen Alpin',16500,'LA-260918',note='Decorative fixture supply only; installation and controls included in Lichtwerk Tirol.'),
 row('bathrooms','Main bathrooms & sanitary fixtures','Quell Studio',28500,'QS-260918',note='Main-house sanitaryware, fittings and vanity package. Optional wellness suite excluded.'),
 row('design','Architecture, interiors & coordination allowance','Morgenlicht Atelier',48000,'MA-260918',note='Concept, design development, coordination and eight site reviews. Statutory fees, measured surveys and specialist reports excluded.'),
 row('logistics','Alpine access & site logistics','Berg Transit',18500,'BT-260918',note='Staged delivery and access allowance. Extraordinary weather delay and road restrictions remain outside this fixed demo allowance.'),
 row('reserve','Client-held renovation contingency','Client allowance',62000,'budget',kind='estimate',note='Uncommitted client reserve for a fictional conversion; not a supplier charge or permission to spend.'),
 row('wellness','Optional garden-level wellness suite','Waldwasser',34800,'WW-260918',optional=True,note='Illustrated wellness room is optional and off by default. €20,000 room fit-out + €14,800 sauna subquote.'),
 row('sauna','Sauna cabin & heater package','Sauna Form',14800,'SA-260918','wellness',True,note='Included in optional Waldwasser package. Parent selection controls whether this scope is enabled; never add twice.'),
 row('terrace','Optional terrace lounge & wind screens','Hochraum Outside',12600,'HO-260918',optional=True,note='Loose outdoor seating and wind-screen allowance, additional to base terrace making good. Terrace image shows this option.'),
 row('unknown','Concealed timber defects & unforeseen ground work','Survey pending',None,'scope',kind='unknown',note='Unknown and excluded from all totals until opened up and assessed. Not a zero-cost allowance.'),
]
quotes=[
 ('AB-260918','Alpen Bauatelier','Main conversion contractor','build',[('Berg Struktur — included BS-260918',92000),('Dach & Holz — included DH-260918',98000),('Haus Technik — included HT-260918',58000)],'Indicative 22-week construction window after approvals.','Separate glazing, joinery, finishes, fixtures, logistics and optional wellness excluded.'),
 ('BS-260918','Berg Struktur','Structural adaptation subcontractor','structure',[('Selective opening-up and internal replanning',29000),('Local supports and enlarged opening works',47000),('Making good and coordination',16000)],'Early works after engineer-reviewed details.','Included in AB-260918. Concealed defects, rock works and specialist engineering fees excluded.'),
 ('DH-260918','Dach & Holz','Roof and envelope subcontractor','roof',[('Roof renewal and weathering layers',56000),('Envelope insulation and airtightness detailing allowance',42000)],'10–12 weeks; weather and procurement dependent.','Included in AB-260918. Original ridge and eaves geometry retained in the concept; no certified performance claim.'),
 ('HT-260918','Haus Technik','Building services coordinator','services',[('Lichtwerk Tirol — included LT-260918',24000),('Klima Berg — included KB-260918',34000)],'First and second fix coordinated with construction.','Included in AB-260918. Decorative light fittings and sanitary fixtures separately priced.'),
 ('LT-260918','Lichtwerk Tirol','Electrical sub-supplier to Haus Technik','electrical',[('Wiring, distribution and outlets',17000),('Controls and commissioning',7000)],'Three staged visits during the main works.','Included in HT-260918, itself included in AB-260918. Final electrical design and local requirements need review.'),
 ('KB-260918','Klima Berg','Heating and ventilation sub-supplier','heating',[('Heating distribution and equipment allowance',22000),('Ventilation and commissioning allowance',12000)],'Equipment lead time 10–14 weeks, illustrative.','Included in HT-260918. Final system sizing, utility capacity and energy assessment excluded from this fictional specification.'),
 ('PW-260918','Panorama Werk','Window and facade specialist','glazing',[('Alpenglas fabrication — included AG-260918',64000),('Frames, fitting and interface detailing',40000)],'14–18 weeks after approved technical drawings.','Structural enlargement is in BS-260918. No thermal, structural or safety certification is represented.'),
 ('AG-260918','Alpenglas','Glazing sub-supplier','glass',[('Glazing fabrication allowance',53000),('Special forms, transport and handling',11000)],'14-week illustrative manufacturing window.','Included in PW-260918. Actual specification requires technical review and site measurements.'),
 ('FA-260918','Fir Atelier','Kitchen and bespoke joinery','joinery',[('Cabinetry, stone worktops and fitting',62000),('Kochraum appliances — included KR-260918',16000)],'12–16 weeks after material and shop-drawing approval.','Includes kitchen, arrival storage and selected bedroom joinery. Loose furniture is separate.'),
 ('KR-260918','Kochraum','Appliance sub-supplier','appliances',[('Induction and extraction',5100),('Ovens and integrated refrigeration',8700),('Dishwasher and installation accessories',2200)],'10–12 weeks after final selection.','Included in FA-260918. Models are intentionally unspecified in this demo.'),
 ('SF-260918','Stein & Faser','Interior finishes specialist','finishes',[('Pale timber floors and installation',18000),('Lime plaster and painting',14500),('General stone finishes',9500)],'Following dry-in and first fix.','Kitchen worktops, bathroom vanity and optional wellness finishes excluded.'),
 ('HE-260918','Hochraum Editions','Furniture and textile allowance','furniture',[('Living and dining furniture',19500),('Bedroom furniture and mattresses',12500),('Curtains, rugs and textiles',10000)],'10–16 weeks after final selections.','Base €42,000; premium selection adds €16,000. Outdoor terrace package is separate HO-260918.'),
 ('LA-260918','Lumen Alpin','Decorative lighting supplier','lighting',[('Dining and kitchen lighting',6500),('Wall and bedside lighting',5200),('Floor and table lamps',4800)],'8–12 week illustrative lead time.','Supply only. Electrical installation and controls are already in LT-260918.'),
 ('QS-260918','Quell Studio','Bathroom supplier','bathrooms',[('Sanitaryware and showers',12200),('Taps and fittings',7100),('Vanities, mirrors and fixture installation',9200)],'10–12 weeks after approved schedule.','Main bathrooms only. Rough-in services are in HT-260918; optional wellness is WW-260918.'),
 ('MA-260918','Morgenlicht Atelier','Architecture and interior design','design',[('Brief, concept and spatial studies',12500),('Design development and specifications',21500),('Procurement coordination and eight site reviews',14000)],'40-week indicative project programme.','Measured surveys, permits, statutory fees and specialist structural, energy or legal reports excluded.'),
 ('BT-260918','Berg Transit','Mountain site logistics','logistics',[('Staged deliveries and access planning',10500),('Handling, storage and site protection',8000)],'Phased through construction and fit-out.','Exceptional weather, road closures and extraordinary lifting requirements excluded.'),
 ('WW-260918','Waldwasser','Optional wellness specialist','wellness',[('Room fit-out and stone finishes',20000),('Sauna Form — included SA-260918',14800)],'10–14 weeks after optional approval.','Optional and unselected in base budget. Shown in concept imagery. Final ventilation, electrical and wet-area detailing require coordination.'),
 ('SA-260918','Sauna Form','Sauna sub-supplier','sauna',[('Timber-lined cabin and bench package',10200),('Heater, controls and fitting allowance',4600)],'10–12 weeks after dimensions agreed.','Included only within selected WW-260918; no independent addition. Final safety specification by appointed specialist.'),
 ('HO-260918','Hochraum Outside','Optional terrace package','terrace',[('Outdoor lounge furniture and textiles',8400),('Wind-screen allowance and placement',4200)],'8–10 weeks after selection.','Additional option. Guarding, structural terrace extension and landscape works excluded.'),
]
materials=[
 ('M01','Existing dark structural timber','Retained beams and selected facade','Repair and reuse subject to condition survey','BS-260918 / DH-260918'),
 ('M02','Pale silver fir','Joinery and selected ceiling infill','Matte tactile finish; sample approval','FA-260918'),
 ('M03','Grey-green natural stone','Floors, worktops and selected walls','Honed texture; actual stone and use-specific performance review','SF-260918 / FA-260918'),
 ('M04','Ivory lime plaster','Walls and sloping ceilings','Warm white; substrate and moisture review','SF-260918'),
 ('M05','Glacier-blue wool','Throws, cushions and arrival bench','Soft accent against pale timber','HE-260918'),
 ('M06','Ivory wool and oatmeal linen','Upholstery and curtains','Layered texture with practical care requirements','HE-260918'),
 ('M07','Brushed pewter tone','Taps, handles and lighting','Finish direction; approved matched samples','QS-260918 / LA-260918'),
 ('M08','Restored tiled stove','Living room heritage anchor','Retain visually; specialist condition and operation review','BS-260918'),
]
interventions=[('R01','Keep','Roof silhouette, eaves and chalet massing','Confirm actual roof and timber condition'),('R02','Keep','Stone plinth and sound structural beams','Survey and repair before concealment'),('R03','Restore','Original tiled stove and selected timber detail','Specialist inspection; no operating-performance claim'),('N01','Open','Valley-facing glazing and selected partitions','Engineered openings and facade coordination'),('N02','Lighten','Pale joinery, plaster and ceiling infill','Sample review with retained dark timber'),('N03','Upgrade','Roof layers, glazing, heating and ventilation','Specialist design and verified system compatibility'),('O01','Optional','Wellness room and terrace lounge','Select before technical design and procurement')]
programme=[('01','Weeks 1–4','Understand the chalet','Measured survey, opening-up strategy and design brief'),('02','Weeks 5–10','Develop & coordinate','Concept, permissions review and specialist design'),('03','Weeks 11–14','Approve & procure','Freeze package scopes; order glazing and joinery'),('04','Weeks 15–30','Repair & transform','Structural work, roof, dry-in and first-fix services'),('05','Weeks 31–36','Fit & finish','Joinery, surfaces, bathrooms and furniture'),('06','Weeks 37–40','Settle & hand over','Commissioning, snagging and seasonal care briefing')]

slides=[]
def s(key,title,subtitle,body='',image=None,section='story',kind='split',points=None,situation='concept'):
    slides.append(dict(key=key,title=title,subtitle=subtitle,body=body,image=image,section=section,kind=kind,points=points or [],situation=situation))
s('cover','Haus\nMorgenlicht.','AN OLD CHALET. A NEW WAY TO LIVE.','Air, light and the mountains. A fictional Austrian chalet conversion / September 2026',image='summer',kind='cover')
s('invitation','A new chapter,\nwith an old soul.','01 / THE INVITATION','For fictional clients Anna and Lukas Leitner, the chalet becomes a generous retreat in every season: open to summer meadows, warm against winter snow, and always connected to the mountains.',image='summer',points=['Imagined location: the Tyrolean Alps, Austria','Illustrative 280 m² interior concept across three levels','Demo 03 / Chalet conversion'])
s('mountains','Leave room\nfor the view.','THE FEELING','Morning air. A clear horizon. The quiet of the mountains before the day begins. The design brings that sense of space indoors through light, calm materials and carefully framed views.',image='mountains',kind='hero',situation='reference')
s('original','A house worth\nkeeping.','02 / THE IMAGINED ORIGINAL','A weathered timber chalet with a generous pitched roof, a stone base and a heavy carved balcony. Its character is the starting point. This is an AI-generated fictional existing-condition study, not a site survey photograph.',image='before-exterior',section='current',situation='before')
s('beforeliving','Warm character.\nClosed-off rooms.','THE ORIGINAL INTERIOR','Dark beams, orange-toned panelling, compact windows and substantial furniture make the imagined living room feel inward-looking. The green tiled stove is a beautiful anchor for its next chapter.',image='before-living',section='current',situation='before')
s('keepchange','Keep the soul.\nOpen the possibilities.','THE CONVERSION STRATEGY','Retain the elements that give the chalet its identity. Introduce contemporary comfort through deliberate, local changes.',section='current',kind='principles',points=['Keep the roof silhouette, stone plinth and sound beams','Restore the tiled stove and selected weathered timber','Open the valley facade and selected internal partitions','Lighten the envelope with pale fir and warm plaster'])
s('exteriorcompare','Same silhouette.\nNew light.','BEFORE / PROPOSED EXTERIOR','A matched concept edit keeps the camera position, roof geometry and landscape recognisable while exploring a lighter facade, simpler balcony and larger view openings. Both images are fictional generated studies.',section='designs',kind='comparison')
s('materials','Mountain materials.\nA lighter touch.','03 / MATERIAL MOOD','Weathered old timber meets pale silver fir, warm ivory plaster and cool grey-green stone. Brushed metal provides a quiet line of detail. Texture does the work that ornament once did.',image='materials',section='moodboards',kind='board')
s('textiles','The warmth\nyou can feel.','TEXTILE & COLOUR MOOD','Ivory wool, oatmeal linen, glacier blue and a small rust accent. Softness belongs to the interior; the mountain view brings all the drama we need.',image='textiles',section='moodboards',kind='board')
s('palette','Snow. Stone.\nSky. Timber.','THE COLOUR LANGUAGE','A fresh, pale foundation with mineral blues and the warmth of timber. Existing dark beams remain deliberate lines within the lighter rooms.',section='moodboards',kind='palette')
s('existingplan','Understand the\noriginal rhythm.','04 / EXISTING LAYOUT STUDY','An imagined main-floor arrangement of separate kitchen, dining, living and arrival rooms. The plan is a storytelling device based on the fictional brief; it is not an existing measured drawing.',image='existing-plan',section='current',kind='plan',situation='before')
s('proposedplan','Open the rooms.\nKeep the refuge.','PROPOSED MAIN FLOOR','Connected cooking, dining and living face the valley, while storage, stairs and practical arrival functions stay contained. Enlarged openings and partition changes require site-specific structural design.',image='proposed-plan',section='designs',kind='plan')
s('living','The mountains,\ninvited inside.','THE REIMAGINED LIVING ROOM','The original beam rhythm and green tiled stove remain. Pale surfaces, softer furniture and a larger valley-facing opening make the same room feel open, generous and full of air.',image='living',section='designs',kind='hero')
s('interiorcompare','The same room.\nA different feeling.','BEFORE / PROPOSED LIVING','A matched interior edit retains the camera, room boundaries, beams and stove. The transformation comes from daylight, restrained joinery and furniture that allows the space to breathe.',section='designs',kind='comparison')
s('section','Light follows\nthe roofline.','SECTION / THE SPATIAL IDEA','Retain the pitched roof and work with its volume. New view openings and lighter ceiling infill bring daylight deeper into the chalet; the garden level holds service space and an optional wellness retreat.',image='section',section='designs',kind='plan')
s('kitchen','Breakfast,\nwith a horizon.','KITCHEN & DINING','Pale silver-fir cabinetry, a mineral stone island and an unhurried dining table create the social heart. Old dark beams keep the room grounded in the original chalet.',image='kitchen',section='designs',kind='hero')
s('details','Fewer materials.\nMore meaning.','DETAILS & SPECIFICATION','Joinery, plaster and stone repeat through the house. Every material meets an older element somewhere, making the conversion feel connected rather than newly assembled.',section='designs',kind='details')
s('bedroom','Wake up\nabove the noise.','THE PRIMARY SUITE','A light-filled room beneath the gable, with wool, soft blue and a view of winter peaks. Retained beams frame the pitched ceiling; the new glazing makes the landscape part of the room.',image='bedroom',section='designs',kind='hero')
s('upperplan','Quiet rooms,\nunder the eaves.','UPPER FLOOR CONCEPT','A primary suite, guest room and shared landing are organised around the existing roof form. Gable openings, headroom and escape arrangements remain subject to measured and technical review.',image='upper-plan',section='designs',kind='plan')
s('arrival','For snowy boots\nand muddy adventures.','THE PRACTICAL ARRIVAL','Pale built-in storage, a soft bench and durable mineral flooring make coming home easy. A calm place to leave skis, walking boots and the weather before entering the living rooms.',image='arrival',section='designs',kind='hero')
s('wellness','Warmth,\nafter the mountain.','OPTIONAL WELLNESS RETREAT','A quiet garden-level room of stone, timber and soft winter light. The illustrated €34,800 wellness suite is optional, including its €14,800 sauna package; it is unselected in the base budget.',image='spa',section='designs',kind='hero')
s('summer','Summer lives\nwith the doors open.','05 / THE SUMMER CHALET','Meadow greens, cool stone and the long light of the Alps. The reworked facade opens generously while retaining the familiar chalet silhouette and its relationship with the slope.',image='summer',section='seasons',kind='hero')
s('terrace','Take the slow\nway through the day.','THE SUMMER TERRACE','A sheltered place for coffee, reading and looking outward. The furniture and wind-screen treatment shown belong to the optional €12,600 terrace package.',image='terrace',section='seasons',kind='hero')
s('winter','A warm light\nin a white landscape.','THE WINTER CHALET','The same renovated chalet, held in snow and evening blue. Warm rooms glow behind the new glazing; timber and stone keep the building rooted in its Alpine setting.',image='winter',section='seasons',kind='hero')
s('seasonpair','One home.\nTwo beautiful worlds.','SUMMER / WINTER','Seasonal studies of the same proposed exterior. The architecture stays constant; light, landscape and daily rituals change around it.',section='seasons',kind='comparison')
s('comfort','Comfort begins\nwith the building.','FABRIC, AIR & LIGHT','Roof and envelope work, carefully specified glazing, and coordinated heating and ventilation support the architectural concept. Actual performance follows surveys, specialist design and commissioning.',section='delivery',kind='comfort')
s('investment','A clear view\nof the conversion.','06 / THE INVESTMENT','€687,500–€703,500 including a €62,000 client-held contingency. Furniture choices create the range. Optional wellness and terrace packages are excluded; concealed defects remain unpriced. Figures are fictional and include assumed VAT.',section='budget',kind='budget')
s('suppliers','Every package.\nEvery layer.','THE SUPPLIER STRUCTURE','Included subquotes explain their parent price. The electrical and heating packages sit inside building services, which sits inside the main conversion contract. Optional wellness remains separate.',section='budget',kind='hierarchy')
s('options','Make it\nyour mountain home.','OPTIONS & SELECTIONS','Base €687,500. Premium furniture adds €16,000; wellness adds €34,800; terrace living adds €12,600. All selections together: €750,900, including contingency and excluding unpriced concealed conditions.',section='budget',kind='options')
s('programme','A thoughtful\ntransformation.','07 / THE PROGRAMME','An indicative 40-week project, with work sequencing shaped by surveys, permissions, long-lead glazing and Alpine weather. No delivery date is guaranteed by this fictional programme.',section='delivery',kind='timeline')
s('scope','Before the\nfirst opening-up.','SCOPE & DECISIONS','Approve the design direction, investigate the actual building, resolve the technical design and select options before placing orders. A conversion begins with understanding what is already there.',section='delivery',kind='principles',points=['All clients, suppliers, quotations and prices are fictional','Before and proposed images are generated concept studies','Plans are unmeasured and not for construction','Surveys, fees, specialist reports and exceptional repairs are excluded'])
s('closing','Come for the mountains.\nStay for the feeling.','HAUS MORGENLICHT / DEMO 03','An old Austrian chalet, opened to a new way of living. Prepared for the fictional Leitner family by Morgenlicht Atelier.',image='winter',section='delivery',kind='cover')

additional_assets=add_visual_studies(OUT,slides)
base=sum((r['amount'] if r['amount'] is not None else r['min_amount'] or 0) for r in budget if not r['included'] and not r['optional']);assert base==687500,base
manifest=dict(slug='haus-morgenlicht',name='Haus Morgenlicht',project_name='Haus Morgenlicht · Austrian chalet demo',location='Tyrolean Alps, Austria · fictional conversion',description='An old chalet. A new way to live. Air, light and mountain views, through summer and winter.',pdf='Haus-Morgenlicht-Presentation.pdf',assets=['summer','winter','before-exterior','before-living','living','kitchen','bedroom','spa','arrival','materials','textiles','mountains','terrace'],plans=['existing-plan','proposed-plan','upper-plan','section'],composed=['exteriorcompare','interiorcompare','seasonpair','palette','details','comfort','suppliers','options','programme'],theme=dict(style='Light Alpine modernism',font='serif',mode='light',light_background='#f4f7f7',background='#243c49',colors=['#edf0eb','#a7c2cd','#d4b692','#748789','#334c5a']),groups=[['story','The story'],['current','The original chalet'],['moodboards','Mood & materials'],['designs','The transformation'],['seasons','Summer & winter'],['budget','The investment'],['delivery','The next chapter']],budget=budget,slides=slides,base_total=base,max_total=703500,all_options_total=750900,quotes=[dict(reference=q[0],vendor=q[1],role=q[2],key=q[3]) for q in quotes])
manifest['assets']+=additional_assets
(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False))
for filename,heads,records in [('budget.csv',list(budget[0]),budget),('materials.csv',['code','material','location','specification','source'],materials),('interventions.csv',['code','approach','scope','review_gate'],interventions),('programme.csv',['stage','timing','phase','deliverable'],programme)]:
    with (OUT/filename).open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=heads);w.writeheader();w.writerows(records if isinstance(records[0],dict) else [dict(zip(heads,x)) for x in records])

def txt(x,y,label,size=15,fill='#334c5a',anchor='start'):
    return f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" fill="{fill}" text-anchor="{anchor}">{e(label)}</text>'
def plan(key):
    old=key=='existing-plan';upper=key=='upper-plan'
    out='<rect width="1200" height="920" fill="#f4f7f4"/>'+txt(60,52,'HAUS MORGENLICHT / '+('IMAGINED EXISTING MAIN FLOOR' if old else 'PROPOSED UPPER FLOOR' if upper else 'PROPOSED MAIN FLOOR'),19)+txt(60,82,'Concept study · same assumed envelope · no measured dimensions · not for construction',12)
    out+='<rect x="80" y="155" width="780" height="565" fill="#ece6d9" stroke="#536772" stroke-width="10"/>'
    if old:
        out+='<path d="M355 155V720M585 155V720M80 370H860" stroke="#536772" stroke-width="8" fill="none"/>'
        out+='<path d="M210 720H275M425 720H490M665 720H735" stroke="#b8c5c8" stroke-width="9"/>'
        rooms=[(205,280,'KITCHEN'),(462,280,'DINING'),(718,280,'STAIR / HALL'),(205,570,'LIVING'),(463,570,'PARLOUR'),(716,570,'ENTRY / STORE')]
        out+='<rect x="115" y="465" width="62" height="74" fill="#657768"/><rect x="225" y="456" width="70" height="162" fill="#bca58a"/><rect x="386" y="476" width="160" height="84" fill="#bca58a"/>'
    elif upper:
        out+='<path d="M450 155V720M650 155V720M80 395H450M650 405H860" stroke="#536772" stroke-width="7" fill="none"/>'
        out+='<path d="M155 720H373M695 720H813" stroke="#8eafbd" stroke-width="10"/>'
        out+='<rect x="170" y="485" width="177" height="150" rx="6" fill="#f7f7f0" stroke="#b2bfc0" stroke-width="2"/><rect x="184" y="497" width="60" height="35" rx="7" fill="#d6e4e7"/><rect x="271" y="497" width="60" height="35" rx="7" fill="#d6e4e7"/><rect x="702" y="493" width="112" height="154" rx="5" fill="#f7f7f0"/>'
        rooms=[(263,285,'BATH / DRESSING'),(263,676,'PRIMARY SUITE'),(546,565,'LANDING'),(755,285,'BATH / STORE'),(755,681,'GUEST ROOM')]
        out+='<path d="M110 175V700M830 175V700" stroke="#b69776" stroke-width="2" stroke-dasharray="8 9"/>'
    else:
        out+='<path d="M80 370H286M590 155V374M590 480V720M590 370H860" stroke="#536772" stroke-width="7" fill="none"/>'
        out+='<path d="M355 170V693M100 370H578M585 390V687" stroke="#c3987c" stroke-width="3" stroke-dasharray="10 9" fill="none"/>'
        out+='<path d="M130 720H539M633 720H818" stroke="#86afc0" stroke-width="12"/>'
        out+='<rect x="102" y="177" width="420" height="40" fill="#d2bb99"/><rect x="170" y="261" width="190" height="65" rx="9" fill="#91a3a4"/><ellipse cx="472" cy="466" rx="67" ry="103" fill="#d2bb99"/><rect x="132" y="485" width="174" height="62" rx="19" fill="#f8f7ef" stroke="#b8c3c2" stroke-width="2"/><rect x="132" y="541" width="62" height="97" rx="16" fill="#f8f7ef" stroke="#b8c3c2" stroke-width="2"/><rect x="250" y="578" width="82" height="49" rx="6" fill="#8fa6aa"/><rect x="105" y="405" width="62" height="62" fill="#657768"/>'
        rooms=[(311,245,'KITCHEN'),(462,613,'DINING'),(285,676,'LIVING / VALLEY VIEW'),(722,285,'STAIR / SERVICES'),(718,540,'ARRIVAL / STORAGE')]
        out+='<path d="M655 428H807V455H655Z" fill="#d2bb99"/>'
    for x,y,label in rooms:out+=txt(x,y,label,13,anchor='middle')
    if old or not upper:
        for y in range(208,333,18):out+=f'<path d="M650 {y}H802" stroke="#b4bbb8" stroke-width="2"/>'
    else:
        for y in range(205,426,20):out+=f'<path d="M476 {y}H620" stroke="#a9babc" stroke-width="2"/>'
    out+='<rect x="92" y="753" width="754" height="47" fill="#dee7e6"/>'+txt(470,782,'BALCONY / TERRACE TOWARD THE VALLEY',13,anchor='middle')
    out+=txt(922,188,'READING THE PLAN',13)
    legend=[('#536772','Retained envelope / walls'),('#86afc0','Proposed view openings'),('#c3987c','Concept removals'),('#657768','Retained tiled stove')]
    if old:legend=[('#536772','Imagined existing walls'),('#b8c5c8','Compact original windows'),('#bca58a','Existing furniture study'),('#657768','Tiled stove')]
    if upper:legend=[('#536772','Envelope and partitions'),('#86afc0','Proposed glazing'),('#b69776','Indicative eaves zone'),('#d6e4e7','Primary bedroom')]
    for i,(colour,label) in enumerate(legend):out+=f'<rect x="925" y="{229+i*54}" width="22" height="8" fill="{colour}"/>'+txt(925,257+i*54,label,12)
    out+=txt(920,610,'Valley direction assumed',11)+txt(920,635,'Room sizes indicative',11)+txt(60,873,'FICTIONAL CONVERSION / CONCEPT ONLY / SEPTEMBER 2026',11)
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 920" role="img"><title>Haus Morgenlicht '+key+'</title>'+out+'</svg>'
for key in ['existing-plan','proposed-plan','upper-plan']:(OUT/'assets'/f'{key}.svg').write_text(plan(key))
sec='<rect width="1400" height="850" fill="#f4f7f4"/>'+txt(62,64,'HAUS MORGENLICHT / LIGHT & LEVELS',22)+txt(62,96,'A conceptual section through the existing roof form and proposed interior',15)
sec+='<path d="M160 340L660 155L1160 340" fill="none" stroke="#6c6358" stroke-width="24"/><path d="M210 343L660 181L1110 343V690H210Z" fill="#eee8da" stroke="#586e77" stroke-width="6"/><path d="M210 444H1110M210 574H1110" stroke="#756d61" stroke-width="13"/>'
sec+='<path d="M366 293V430M968 292V430M366 461V560M969 461V560" stroke="#84adbf" stroke-width="14"/><path d="M275 260L400 347L520 394M1049 260L925 349L790 393M1140 480L954 492L791 525" stroke="#d0b77b" stroke-width="5" fill="none"/>'
sec+='<path d="M187 696L1170 659L1308 693" stroke="#929e87" stroke-width="7" fill="none"/><rect x="557" y="505" width="83" height="55" fill="#6a7d68"/><rect x="580" y="364" width="191" height="66" fill="#f9f8f0" stroke="#adbfc2"/>'
for x,y,label in [(702,322,'SLEEP / PITCHED ROOF'),(755,505,'LIVE / VALLEY OPENINGS'),(658,634,'GARDEN LEVEL / SERVICE + OPTIONAL WELLNESS')]:sec+=txt(x,y,label,16,anchor='middle')
sec+=txt(64,759,'Keep the roof silhouette. Lighten the infill. Frame the view.',22)+txt(64,807,'Schematic only · levels, structure, headroom and opening details require survey and engineering',13)
(OUT/'assets/section.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1400 850" role="img"><title>Haus Morgenlicht conceptual section</title>'+sec+'</svg>')

CSS=(OUT/'presentation.css').read_text()
def img(s):return f'<img src="assets/{s["image"]}.{"svg" if s["image"] in manifest["plans"] else "webp"}" alt="{e(s["title"].replace(chr(10)," "))} — fictional chalet concept">'
def content(s):
    head=f'<div class="eyebrow">{e(s["subtitle"])}</div><h1>{e(s["title"])}</h1>';desc=f'<p>{e(s["body"])}</p>';kind=s['kind']
    if kind in ('cover','hero'):return img(s)+f'<div class="overlay">{head}{desc}</div>'
    if kind=='board':return f'<div class="board-layout"><div>{head}{desc}</div>{img(s)}</div>'
    if s['image']:
        pts='<ul>'+''.join(f'<li>{e(x)}</li>' for x in s['points'])+'</ul>' if s['points'] else ''
        return f'<div class="split-layout"><div class="copy">{head}{desc}{pts}</div>{img(s)}</div>'
    extra=''
    if s['points']:extra='<div class="points">'+''.join(f'<div><small>{n:02d}</small>{e(x)}</div>' for n,x in enumerate(s['points'],1))+'</div>'
    if kind=='comparison':
        pair={'exteriorcompare':[('before-exterior','IMAGINED ORIGINAL'),('summer','PROPOSED CONVERSION')],'interiorcompare':[('before-living','IMAGINED ORIGINAL'),('living','PROPOSED CONVERSION')],'seasonpair':[('summer','SUMMER / PROPOSED'),('winter','WINTER / SAME PROPOSAL')]}[s['key']]
        extra='<div class="diptych">'+''.join(f'<figure><img src="assets/{key}.webp" alt="{caption}"><figcaption>{caption}</figcaption></figure>' for key,caption in pair)+'</div>'
    if kind=='palette':extra='<div class="swatches">'+''.join(f'<div class="swatch" style="background:{c}">{label}<small>{c.upper()}</small></div>' for c,label in zip(manifest['theme']['colors'],['Snow linen','Glacier light','Pale fir','Mountain stone','Evening blue']))+'</div>'
    if kind=='details':extra='<table><tr><th>Material</th><th>Where it belongs</th><th>Design intent</th></tr>'+''.join(f'<tr><td>{e(r[1])}</td><td>{e(r[2])}</td><td>{e(r[3])}</td></tr>' for r in materials[:7])+'</table>'
    if kind=='budget':
        rs=[r for r in budget if not r['included'] and not r['optional'] and r['kind']!='unknown']
        extra='<table><tr><th>Package</th><th>Basis</th><th>Investment incl. assumed VAT</th></tr>'+''.join(f'<tr><td>{e(r["label"])}</td><td>{"Allowance" if r["kind"]=="estimate" else "Fictional quote"}</td><td>{money(r["amount"]) if r["amount"] is not None else money(r["min_amount"])+"–"+money(r["max_amount"])}</td></tr>' for r in rs)+'</table><div class="total"><span>Known conversion range</span><span>€687,500–€703,500</span></div>'
    if kind in ('options','comfort'):
        cards=[('Premium furniture','+ €16,000','A fuller specification of wool, rugs and loose furniture. Base allowance €42,000.'),('Wellness retreat','+ €34,800','Garden-level fit-out with included sauna package. Illustrated, unselected in the base.'),('Terrace living','+ €12,600','Outdoor lounge and wind-screen package. Additional to base works.')] if kind=='options' else [('Fabric','01','Renew roof layers and coordinate insulation, glazing and moisture strategy.'),('Fresh air','02','Resolve heating and ventilation together, with specialist design and commissioning.'),('Daylight','03','Open selected views and lighten interior surfaces, keeping the old roof and beams legible.')]
        extra='<div class="cards">'+''.join(f'<article class="card"><h3>{a}</h3><strong>{b}</strong><p>{c}</p></article>' for a,b,c in cards)+'</div>'
    if kind=='timeline':extra='<div class="timeline-grid">'+''.join(f'<article><small>{b}</small><h3>{c}</h3><p>{d}</p></article>' for a,b,c,d in programme)+'</div>'
    if kind=='hierarchy':extra='<div class="tree"><article><h3>Alpen Bauatelier / €248,000</h3><div class="child">Berg Struktur / €92,000 included</div><div class="child">Dach & Holz / €98,000 included</div><div class="child">Haus Technik / €58,000 included<div class="child">Lichtwerk Tirol / €24,000 included<br>Klima Berg / €34,000 included</div></div></article><article><h3>Panorama Werk / €104,000</h3><div class="child">Alpenglas / €64,000 included</div><br><h3>Optional wellness / €34,800</h3><div class="child">Sauna Form / €14,800 included</div><small>Parent package begins unselected. Included subquotes never increase the parent total.</small></article></div>'
    return f'<div class="inner">{head}{desc}{extra}</div>'
body=''.join(f'<section class="slide {s["kind"]}" id="{s["key"]}" aria-label="Slide {i}: {e(s["title"])}">{content(s)}<footer class="folio"><span>MORGENLICHT / ATELIER</span><b>FICTIONAL DEMO · GENERATED CONCEPT STUDIES</b><span>{i:02d} / {len(slides):02d}</span></footer></section>' for i,s in enumerate(slides,1))
js='''<script>const slides=[...document.querySelectorAll('.slide')];let current=0;const o=new IntersectionObserver(entries=>{for(const x of entries)if(x.isIntersecting){current=slides.indexOf(x.target);document.querySelector('#counter').textContent=`${current+1} / ${slides.length}`;}},{threshold:.55});slides.forEach(x=>o.observe(x));function move(n){current=Math.max(0,Math.min(slides.length-1,current+n));slides[current].scrollIntoView({behavior:'smooth'});}document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);document.querySelector('#full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','PageDown','PageUp'].includes(e.key)){e.preventDefault();move(['ArrowRight','PageDown'].includes(e.key)?1:-1);}});function scale(){document.documentElement.style.setProperty('--scale',Math.min(1,innerWidth/1440))}scale();addEventListener('resize',scale);</script>'''
(OUT/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Haus Morgenlicht — Air, light & mountains</title><style>'+CSS+'</style><body>'+body+f'<nav class="toolbar" aria-label="Presentation controls"><button id="prev" aria-label="Previous slide">←</button><span id="counter">1 / {len(slides)}</span><button id="next" aria-label="Next slide">→</button><button id="full">Fullscreen</button><a href="{manifest["pdf"]}">PDF</a><a href="supplier-index.html">Project pack</a></nav>'+js+'</body></html>')

DOC=(OUT/'quote.css').read_text()
def document(title,body):return f'<!doctype html><html lang="en"><meta charset="utf-8"><title>{e(title)}</title><style>{DOC}</style><body>{body}</body></html>'
for ref,vendor,role,key,lines,lead,exclusions in quotes:
    total=sum(x[1] for x in lines);net=round(total/1.2,2);tax=round(total-net,2);r=next(x for x in budget if x['key']==key)
    body=f'<div class="tag">{e(role)} / Fictional supplier</div><h1>{e(vendor)}</h1><p>{vendor.lower().replace(" ",".").replace("&","and")}@example.test</p><div class="banner"><strong>FICTIONAL DEMO QUOTATION — NOT A COMMERCIAL OFFER</strong><br>Created for Haus Morgenlicht. No real supplier has issued this document.</div><div class="meta"><div><strong>Prepared for</strong><br>Anna & Lukas Leitner (fictional)<br>Haus Morgenlicht / Austrian Alps<br>Via Morgenlicht Atelier</div><div><strong>Reference</strong> {ref}<br><strong>Date</strong> 18 September 2026<br><strong>Illustrative validity</strong> 30 days<br><strong>Currency</strong> EUR</div></div><h2>{e(r["label"])}</h2><table><tr><th>Package scope</th><th>Amount incl. assumed VAT</th></tr>'+''.join(f'<tr><td>{e(label)}</td><td>{money(v)}</td></tr>' for label,v in lines)+f'</table><div class="total"><span>{"Base allowance" if key=="furniture" else "Package total"}</span><strong>{money(total)}</strong></div><p>Illustrative net €{net:,.2f} + assumed 20% VAT €{tax:,.2f} = €{total:,.2f}. Uniform fictional VAT assumption for demonstration arithmetic only.</p><h2>Budget relationship</h2><p>{e(r["note"])}</p><h2>Programme & commercial assumptions</h2><p>{e(lead)} Payment example: 40% on order, 40% before delivery, 20% after handover. No payment is requested. Actual quantities and suitability follow site assessment.</p><h2>Exclusions & qualifications</h2><p>{e(exclusions)}</p><footer>HAUS MORGENLICHT / {ref} / Fictional names and figures. No signature, registration number or bank details. Not for purchasing or construction.</footer>'
    (OUT/'suppliers'/f'{ref}.html').write_text(document(ref+' / '+vendor,body))
scope='''<div class="tag">Haus Morgenlicht / Scope schedule / September 2026</div><h1>Understanding the conversion.</h1><div class="banner">FICTIONAL DEMO DOCUMENT / Illustrative assumptions, not a contract.</div><h2>Known investment</h2><p>Construction, glazing, joinery, finishes, furniture, decorative lighting, main bathrooms, design coordination, logistics and a €62,000 client reserve. Base €687,500; premium furniture selection €703,500. Every figure is fictional and uses a uniformly assumed VAT-inclusive basis of 20% solely for demo arithmetic.</p><h2>Included subquotes</h2><p>Alpen Bauatelier €248,000 includes Berg Struktur €92,000, Dach & Holz €98,000 and Haus Technik €58,000. Haus Technik includes Lichtwerk Tirol €24,000 and Klima Berg €34,000. Panorama Werk €104,000 includes Alpenglas €64,000. Fir Atelier €78,000 includes Kochraum €16,000. Included subquotes are never added twice.</p><h2>Optional packages</h2><p>Wellness €34,800 includes Sauna Form €14,800. The parent begins unselected, so the entire optional scope stays outside the base total. Terrace lounge and wind screens add €12,600. Premium furniture adds €16,000. Selecting all options and premium furniture gives €750,900. Wellness and terrace imagery shows these optional packages.</p><h2>Conversion boundaries</h2><p>The design retains the roof silhouette, sound main beams, stone plinth and selected heritage detail. All images, including the imagined original chalet, are generated studies. Before/proposed pairs preserve visual identity but do not establish an existing measured condition. Plans and the 280 m² brief are illustrative and not suitable for construction.</p><h2>Package interfaces</h2><p>Structural window enlargement is in Berg Struktur; frames and glazing are in Panorama Werk. Wiring and controls are in Lichtwerk Tirol; decorative light supply is in Lumen Alpin. Kitchen worktops are in Fir Atelier; general floors and wall finishes are in Stein & Faser. The retained tiled stove requires specialist inspection before any real operational proposal.</p><h2>Unknown and excluded</h2><p>Concealed timber defects, unexpected ground or rock works, measured surveys, statutory fees, permits, specialist structural/energy reports, property purchase, utility upgrades and extraordinary weather or access disruption are not priced in the known totals. Unknown conditions are not zero-cost items. No compliance, thermal performance or completion-date guarantee is made.</p><h2>Decision gates</h2><p>Commission a measured survey and condition assessment; agree the retention and opening-up strategy; review local permissions and specialist designs; approve materials and windows; select options; then freeze procurement packages. The 40-week programme and all supplier lead times are fictional planning assumptions.</p><footer>HAUS MORGENLICHT / DEMO 03 / No purchase, client approval, supplier acceptance or construction instruction is represented.</footer>'''
(OUT/'scope.html').write_text(document('Haus Morgenlicht / Scope & assumptions',scope))
index='<div class="tag">Haus Morgenlicht / Project library</div><h1>The complete mountain story.</h1><div class="banner">Fictional demonstration. All supplier documents, clients and costs are invented.</div><p><a href="index.html">Presentation</a> · <a href="Haus-Morgenlicht-Presentation.pdf">PDF deck</a> · <a href="budget.csv">Budget</a> · <a href="materials.csv">Materials</a> · <a href="interventions.csv">Interventions</a> · <a href="programme.csv">Programme</a> · <a href="scope.pdf">Scope PDF</a></p><table><tr><th>Document</th><th>Supplier</th><th>Relationship</th></tr>'
for q in quotes:
    r=next(x for x in budget if x['key']==q[3]);rel='Included subquote' if r['included'] else 'Optional package' if r['optional'] else 'Allowance' if r['kind']=='estimate' else 'Top-level package'
    index+=f'<tr><td><a href="suppliers/{q[0]}.pdf">{q[0]} PDF</a> · <a href="suppliers/{q[0]}.html">HTML</a></td><td>{q[1]}</td><td>{rel}</td></tr>'
(OUT/'supplier-index.html').write_text(document('Haus Morgenlicht / Project library',index+'</table>'))
print(f'Built {len(slides)} chalet slides, {len(manifest["plans"])} plans, {len(quotes)} quotes and {len(budget)} budget rows.')
