-- Studiodeck: complete database schema
-- Snapshot: 2026-09-28, after removal of project activity history.
-- Database engine: SQLite (the engine used by app/bootstrap.php).
-- 92 tables, 553 columns, 24 explicit indexes, 1 trigger.
--
-- Generated by initializing a fresh database through app/bootstrap.php, including
-- every SQL schema file and PHP migration. Tables are listed alphabetically;
-- each column retains its exact declared type, default and constraints.
-- PRIMARY KEY / UNIQUE constraints also create SQLite-managed indexes.
--
-- Type conventions used by the application:
--   TEXT: strings, IDs, serialized JSON and text-formatted dates/timestamps.
--   INTEGER: whole numbers, 0/1 flags, integer timestamps and monetary cents.
--   BLOB: binary file contents, previews, images and avatars.
-- Timestamp representation follows each column's application usage; do not
-- assume every *_at column has the same representation.
--
-- This file can initialize an empty SQLite database. It is a schema snapshot,
-- not an upgrade script for an existing database. Runtime schema changes remain
-- defined in app/bootstrap.php, app/*_schema.sql, app/schema.sql and the PHP
-- migration functions. Regenerate this snapshot when those definitions change.
-- No project/user data is included. The final INSERT only records the migration
-- versions already reflected here, so startup does not reapply old ALTERs.
-- Retired tables events and event_questions are intentionally absent.

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

-- Tables

-- assets (4 columns)
CREATE TABLE assets (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    category TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- billing_changes (16 columns)
CREATE TABLE billing_changes (
    id TEXT PRIMARY KEY,
    studio_id TEXT NOT NULL REFERENCES studios(id),
    subscription_id TEXT NOT NULL,
    plan TEXT NOT NULL,
    extra_projects INTEGER NOT NULL,
    extra_seats INTEGER NOT NULL,
    parameters TEXT NOT NULL,
    snapshot TEXT NOT NULL,
    amount INTEGER NOT NULL,
    currency TEXT NOT NULL,
    proration_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    effective_at INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'preview',
    schedule_id TEXT,
    invoice_url TEXT
);

-- billing_notices (8 columns)
CREATE TABLE billing_notices (
    notice_key TEXT PRIMARY KEY,
    studio_id TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt INTEGER NOT NULL DEFAULT 0
);

-- billing_orders (17 columns)
CREATE TABLE billing_orders (
    id TEXT PRIMARY KEY,
    studio_id TEXT NOT NULL REFERENCES studios(id),
    project_id TEXT,
    actor_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    plan TEXT NOT NULL,
    price_id TEXT NOT NULL,
    checkout_id TEXT UNIQUE,
    checkout_url TEXT,
    payment_id TEXT UNIQUE,
    invoice_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at INTEGER NOT NULL,
    paid_at INTEGER,
    expires_at INTEGER NOT NULL,
    parameters TEXT NOT NULL DEFAULT '{}',
    error TEXT NOT NULL DEFAULT ''
);

-- billing_trials (3 columns)
CREATE TABLE billing_trials (
    user_id TEXT PRIMARY KEY REFERENCES users(id),
    studio_id TEXT NOT NULL,
    started_at INTEGER NOT NULL
);

-- billing_usage (4 columns)
CREATE TABLE billing_usage (
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    window TEXT NOT NULL,
    used INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(project_id,kind,window)
);

-- budget_choices (5 columns)
CREATE TABLE budget_choices (
    budget_item_id TEXT PRIMARY KEY REFERENCES budget_items(id) ON DELETE CASCADE,
    selected INTEGER NOT NULL DEFAULT 0,
    range_percent INTEGER NOT NULL DEFAULT 0 CHECK(range_percent BETWEEN 0 AND 100),
    updated_by TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- budget_items (17 columns)
CREATE TABLE budget_items (
    id TEXT PRIMARY KEY,
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    parent_id TEXT REFERENCES budget_items(id),
    source_version_id TEXT REFERENCES file_versions(id),
    label TEXT NOT NULL,
    vendor TEXT NOT NULL DEFAULT '',
    amount_cents INTEGER,
    kind TEXT NOT NULL DEFAULT 'estimate',
    included INTEGER NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    min_amount_cents INTEGER,
    max_amount_cents INTEGER,
    is_optional INTEGER NOT NULL DEFAULT 0,
    source_key TEXT NOT NULL DEFAULT '',
    relationship_origin TEXT NOT NULL DEFAULT 'legacy',
    relationship_evidence TEXT NOT NULL DEFAULT '',
    relationship_locked INTEGER NOT NULL DEFAULT 0
);

-- budget_link_suggestions (9 columns)
CREATE TABLE budget_link_suggestions (
    id TEXT PRIMARY KEY,
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    child_id TEXT NOT NULL REFERENCES budget_items(id) ON DELETE CASCADE,
    parent_id TEXT NOT NULL REFERENCES budget_items(id) ON DELETE CASCADE,
    included INTEGER CHECK(included IN (0,1)),
    evidence TEXT NOT NULL,
    confidence TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','dismissed')),
    created_at TEXT NOT NULL,
    UNIQUE(iteration_id,child_id,parent_id)
);

-- budget_match_checks (4 columns)
CREATE TABLE budget_match_checks (
    iteration_id TEXT PRIMARY KEY REFERENCES iterations(id) ON DELETE CASCADE,
    result TEXT NOT NULL,
    warning TEXT NOT NULL DEFAULT '',
    checked_at TEXT NOT NULL
);

-- check_image_text (3 columns)
CREATE TABLE check_image_text (
    fingerprint TEXT PRIMARY KEY,
    version_id TEXT NOT NULL REFERENCES file_versions(id) ON DELETE CASCADE,
    text TEXT NOT NULL
);

-- check_page_previews (3 columns)
CREATE TABLE check_page_previews (
    version_id TEXT NOT NULL REFERENCES file_versions(id) ON DELETE CASCADE,
    page INTEGER NOT NULL,
    data BLOB NOT NULL,
    PRIMARY KEY(version_id,page)
);

-- check_source_cache (4 columns)
CREATE TABLE check_source_cache (
    iteration_id TEXT NOT NULL REFERENCES iterations(id) ON DELETE CASCADE,
    source_key TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    result TEXT NOT NULL,
    PRIMARY KEY(iteration_id,source_key)
);

-- check_source_roles (3 columns)
CREATE TABLE check_source_roles (
    iteration_id TEXT NOT NULL REFERENCES iterations(id) ON DELETE CASCADE,
    source_key TEXT NOT NULL,
    role TEXT NOT NULL,
    PRIMARY KEY(iteration_id,source_key)
);

-- checklist_threads (3 columns)
CREATE TABLE checklist_threads (
    iteration_id TEXT NOT NULL,
    question_id TEXT NOT NULL,
    root_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    PRIMARY KEY(iteration_id,question_id),
    FOREIGN KEY(iteration_id,question_id) REFERENCES open_questions(iteration_id,id) ON DELETE CASCADE
);

-- client_login_grants (2 columns)
CREATE TABLE client_login_grants (
    token_hash TEXT PRIMARY KEY REFERENCES login_tokens(token_hash) ON DELETE CASCADE,
    share_id TEXT NOT NULL
);

-- comment_attachments (2 columns)
CREATE TABLE comment_attachments (
    comment_id TEXT PRIMARY KEY REFERENCES comments(id) ON DELETE CASCADE,
    version_id TEXT NOT NULL REFERENCES file_versions(id)
);

-- comment_confirmations (7 columns)
CREATE TABLE comment_confirmations (
    comment_id TEXT PRIMARY KEY REFERENCES comments(id) ON DELETE CASCADE,
    recipient TEXT NOT NULL,
    recipient_name TEXT NOT NULL,
    amount_cents INTEGER,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','confirmed','withdrawn')),
    decided_by TEXT,
    decided_at TEXT
);

-- comment_mentions (3 columns)
CREATE TABLE comment_mentions (
    comment_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY(comment_id,email)
);

-- comment_reads (3 columns)
CREATE TABLE comment_reads (
    comment_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    person_key TEXT NOT NULL,
    read_at TEXT NOT NULL,
    PRIMARY KEY(comment_id,person_key)
);

-- comments (9 columns)
CREATE TABLE comments (
    id TEXT PRIMARY KEY,
    annotation TEXT,
    parent_id TEXT REFERENCES comments(id) ON DELETE CASCADE,
    answered INTEGER NOT NULL DEFAULT 0 CHECK(answered IN (0,1)),
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    slide TEXT NOT NULL,
    author TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- communication_audiences (2 columns)
CREATE TABLE communication_audiences (
    root_id TEXT PRIMARY KEY REFERENCES comments(id) ON DELETE CASCADE,
    audience TEXT NOT NULL CHECK(audience IN ('studio','shared'))
);

-- communication_messages (6 columns)
CREATE TABLE communication_messages (
    comment_id TEXT PRIMARY KEY REFERENCES comments(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK(type IN ('message','question','todo','confirmation','price_adjustment')),
    assignee TEXT NOT NULL DEFAULT '',
    assignee_name TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    question_id TEXT
);

-- communication_threads (2 columns)
CREATE TABLE communication_threads (
    comment_id TEXT PRIMARY KEY REFERENCES comments(id) ON DELETE CASCADE,
    title TEXT NOT NULL
);

-- communication_topic_history (8 columns)
CREATE TABLE communication_topic_history (
    id TEXT PRIMARY KEY,
    root_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    actor TEXT NOT NULL,
    from_type TEXT NOT NULL,
    to_type TEXT NOT NULL,
    assignee_name TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

-- communication_topics (7 columns)
CREATE TABLE communication_topics (
    root_id TEXT PRIMARY KEY REFERENCES comments(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK(type IN ('conversation','todo','approval')),
    assignee TEXT NOT NULL DEFAULT '',
    assignee_name TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    question_id TEXT,
    related_root_id TEXT REFERENCES comments(id) ON DELETE SET NULL
);

-- confirmation_budget_links (2 columns)
CREATE TABLE confirmation_budget_links (
    budget_item_id TEXT PRIMARY KEY REFERENCES budget_items(id) ON DELETE CASCADE,
    comment_id TEXT NOT NULL REFERENCES comment_confirmations(comment_id) ON DELETE CASCADE
);

-- consistency_findings (11 columns)
CREATE TABLE consistency_findings (
    id TEXT PRIMARY KEY,
    iteration_id TEXT NOT NULL REFERENCES iterations(id) ON DELETE CASCADE,
    fingerprint TEXT NOT NULL,
    title TEXT NOT NULL,
    explanation TEXT NOT NULL,
    question TEXT NOT NULL DEFAULT '',
    severity TEXT NOT NULL,
    evidence TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved','dismissed')),
    question_id TEXT,
    created_at TEXT NOT NULL
);

-- consistency_runs (5 columns)
CREATE TABLE consistency_runs (
    iteration_id TEXT PRIMARY KEY REFERENCES iterations(id) ON DELETE CASCADE,
    fingerprint TEXT NOT NULL,
    warnings TEXT NOT NULL,
    source_count INTEGER NOT NULL,
    checked_at TEXT NOT NULL
);

-- contacts (6 columns)
CREATE TABLE contacts (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT ''
);

-- conversation_grant_sources (2 columns)
CREATE TABLE conversation_grant_sources (
    grant_id TEXT PRIMARY KEY REFERENCES conversation_grants(id) ON DELETE CASCADE,
    source_grant_id TEXT NOT NULL REFERENCES conversation_grants(id) ON DELETE CASCADE
);

-- conversation_grants (8 columns)
CREATE TABLE conversation_grants (
    id TEXT PRIMARY KEY,
    root_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    invited_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    revoked INTEGER NOT NULL DEFAULT 0,
    UNIQUE(root_id,email)
);

-- conversation_login_grants (2 columns)
CREATE TABLE conversation_login_grants (
    token_hash TEXT PRIMARY KEY REFERENCES login_tokens(token_hash) ON DELETE CASCADE,
    grant_id TEXT NOT NULL REFERENCES conversation_grants(id) ON DELETE CASCADE
);

-- conversation_outbox (7 columns)
CREATE TABLE conversation_outbox (
    id TEXT PRIMARY KEY,
    comment_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    grant_id TEXT NOT NULL REFERENCES conversation_grants(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'queued',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt INTEGER NOT NULL DEFAULT 0,
    error TEXT NOT NULL DEFAULT '',
    UNIQUE(comment_id,grant_id)
);

-- document_images (5 columns)
CREATE TABLE document_images (
    version_id TEXT NOT NULL,
    page_number INTEGER NOT NULL,
    number INTEGER NOT NULL,
    metadata TEXT NOT NULL,
    data BLOB NOT NULL,
    PRIMARY KEY(version_id,page_number,number),
    FOREIGN KEY(version_id,page_number) REFERENCES document_pages(version_id,number) ON DELETE CASCADE
);

-- document_pages (5 columns)
CREATE TABLE document_pages (
    version_id TEXT NOT NULL REFERENCES file_versions(id),
    number INTEGER NOT NULL,
    text TEXT NOT NULL,
    metadata TEXT NOT NULL,
    preview BLOB,
    PRIMARY KEY(version_id,number)
);

-- drive_connections (7 columns)
CREATE TABLE drive_connections (
    user_id TEXT NOT NULL,
    studio_id TEXT NOT NULL,
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    email TEXT NOT NULL DEFAULT '',
    generation TEXT NOT NULL,
    PRIMARY KEY(user_id,studio_id),
    FOREIGN KEY(studio_id,user_id) REFERENCES studio_members(studio_id,user_id) ON DELETE CASCADE
);

-- drive_oauth_states (6 columns)
CREATE TABLE drive_oauth_states (
    state_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    studio_id TEXT NOT NULL,
    session_hash TEXT NOT NULL,
    verifier TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    FOREIGN KEY(studio_id,user_id) REFERENCES studio_members(studio_id,user_id) ON DELETE CASCADE
);

-- email_outbox (11 columns)
CREATE TABLE email_outbox (
    id TEXT PRIMARY KEY,
    comment_id TEXT NOT NULL REFERENCES comments(id),
    person_key TEXT NOT NULL,
    email TEXT NOT NULL,
    user_id TEXT,
    share_id TEXT,
    url TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt INTEGER NOT NULL DEFAULT 0,
    error TEXT NOT NULL DEFAULT '',
    UNIQUE(comment_id,email)
);

-- file_versions (13 columns)
CREATE TABLE file_versions (
    id TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL REFERENCES assets(id),
    parent_id TEXT REFERENCES file_versions(id),
    number INTEGER NOT NULL,
    name TEXT NOT NULL,
    mime TEXT NOT NULL,
    size INTEGER NOT NULL,
    sha256 TEXT NOT NULL,
    data BLOB NOT NULL,
    preview BLOB,
    extracted_text TEXT NOT NULL DEFAULT '',
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    UNIQUE(asset_id, number)
);

-- iteration_covers (2 columns)
CREATE TABLE iteration_covers (
    iteration_id TEXT PRIMARY KEY REFERENCES iterations(id) ON DELETE CASCADE,
    slide_id TEXT NOT NULL,
    FOREIGN KEY(iteration_id,slide_id) REFERENCES presentation_slides(iteration_id,id) ON DELETE CASCADE
);

-- iteration_files (4 columns)
CREATE TABLE iteration_files (
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    asset_id TEXT NOT NULL REFERENCES assets(id),
    version_id TEXT NOT NULL REFERENCES file_versions(id),
    category TEXT NOT NULL,
    PRIMARY KEY(iteration_id,asset_id)
);

-- iteration_pack_items (7 columns)
CREATE TABLE iteration_pack_items (
    iteration_id TEXT NOT NULL REFERENCES iterations(id) ON DELETE CASCADE,
    item_id TEXT NOT NULL REFERENCES studio_pack_items(id),
    version_id TEXT NOT NULL REFERENCES studio_pack_versions(id),
    asset_id TEXT REFERENCES assets(id),
    slide_id TEXT,
    excluded INTEGER NOT NULL DEFAULT 0,
    fingerprint TEXT NOT NULL DEFAULT '',
    PRIMARY KEY(iteration_id,item_id)
);

-- iterations (8 columns)
CREATE TABLE iterations (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    number INTEGER NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    locked INTEGER NOT NULL DEFAULT 0,
    theme TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    UNIQUE(project_id, number)
);

-- job_dismissals (2 columns)
CREATE TABLE job_dismissals (
    job_id TEXT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,
    dismissed_at TEXT NOT NULL
);

-- jobs (10 columns)
CREATE TABLE jobs (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    version_id TEXT REFERENCES file_versions(id),
    type TEXT NOT NULL,
    payload TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'queued',
    error TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    started_at TEXT
);

-- login_tokens (3 columns)
CREATE TABLE login_tokens (
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    expires_at INTEGER NOT NULL
);

-- migrations (1 columns)
CREATE TABLE migrations (
    name TEXT PRIMARY KEY
);

-- open_question_replies (6 columns)
CREATE TABLE open_question_replies (
    id TEXT PRIMARY KEY,
    iteration_id TEXT NOT NULL,
    question_id TEXT NOT NULL,
    author TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY(iteration_id,question_id) REFERENCES open_questions(iteration_id,id) ON DELETE CASCADE
);

-- open_questions (19 columns)
CREATE TABLE open_questions (
    id TEXT NOT NULL,
    iteration_id TEXT NOT NULL REFERENCES iterations(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'clarification' CHECK(kind IN ('answered','clarification','preference')),
    reason TEXT NOT NULL DEFAULT '',
    answer TEXT NOT NULL DEFAULT '',
    citations TEXT NOT NULL DEFAULT '[]',
    origin TEXT NOT NULL DEFAULT 'designer',
    published INTEGER NOT NULL DEFAULT 0,
    dismissed INTEGER NOT NULL DEFAULT 0,
    resolved INTEGER NOT NULL DEFAULT 0,
    edited INTEGER NOT NULL DEFAULT 0,
    fingerprint TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    accepted INTEGER NOT NULL DEFAULT 0,
    item_type TEXT NOT NULL DEFAULT 'question' CHECK(item_type IN ('question','action')),
    responsible TEXT NOT NULL DEFAULT '',
    source_comment_id TEXT REFERENCES comments(id) ON DELETE SET NULL,
    confirmation_id TEXT REFERENCES comment_confirmations(comment_id) ON DELETE SET NULL,
    PRIMARY KEY(iteration_id,id)
);

-- person_profiles (7 columns)
CREATE TABLE person_profiles (
    person_key TEXT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    color TEXT NOT NULL DEFAULT '',
    avatar BLOB,
    email_comments INTEGER NOT NULL DEFAULT 1,
    language TEXT NOT NULL DEFAULT '',
    email_mentions_only INTEGER NOT NULL DEFAULT 0
);

-- presentation_slides (13 columns)
CREATE TABLE "presentation_slides" (
    id TEXT NOT NULL,
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    source_version_id TEXT REFERENCES file_versions(id),
    page_number INTEGER NOT NULL DEFAULT 0,
    image_number INTEGER NOT NULL DEFAULT 0,
    type TEXT NOT NULL,
    situation TEXT NOT NULL DEFAULT 'unknown',
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    metadata TEXT NOT NULL DEFAULT '{}',
    position INTEGER NOT NULL,
    image_version_id TEXT REFERENCES slide_image_versions(id),
    manual INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(iteration_id,id)
);

-- product_feedback (18 columns)
CREATE TABLE product_feedback (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    studio_id TEXT REFERENCES studios(id) ON DELETE SET NULL,
    request_key TEXT NOT NULL,
    category TEXT NOT NULL CHECK(category IN ('broken','friction','missing','positive','other')),
    area TEXT NOT NULL,
    goal TEXT NOT NULL,
    detail TEXT NOT NULL,
    impact TEXT NOT NULL CHECK(impact IN ('','minor','slows','blocked')),
    frequency TEXT NOT NULL CHECK(frequency IN ('first','sometimes','often')),
    contact_allowed INTEGER NOT NULL DEFAULT 0 CHECK(contact_allowed IN (0,1)),
    screen TEXT NOT NULL,
    app_version TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','reviewing','clarification','planned','shipped','not_pursuing')),
    theme TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(user_id,request_key)
);

-- product_feedback_images (3 columns)
CREATE TABLE product_feedback_images (
    feedback_id TEXT PRIMARY KEY REFERENCES product_feedback(id) ON DELETE CASCADE,
    data BLOB NOT NULL,
    mime TEXT NOT NULL
);

-- product_feedback_outbox (6 columns)
CREATE TABLE product_feedback_outbox (
    feedback_id TEXT PRIMARY KEY REFERENCES product_feedback(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','sending','sent','logged','failed','cancelled')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt INTEGER NOT NULL DEFAULT 0,
    error TEXT NOT NULL DEFAULT ''
);

-- project_access_grants (5 columns)
CREATE TABLE project_access_grants (
    order_id TEXT PRIMARY KEY REFERENCES billing_orders(id),
    project_id TEXT NOT NULL,
    paid_at INTEGER NOT NULL,
    days INTEGER NOT NULL,
    revoked INTEGER NOT NULL DEFAULT 0
);

-- project_client_members (4 columns)
CREATE TABLE project_client_members (
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    email TEXT NOT NULL COLLATE NOCASE,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY(project_id,email)
);

-- project_coverage (5 columns)
CREATE TABLE project_coverage (
    project_id TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    source TEXT NOT NULL CHECK(source IN ('trial','project_pass','subscription','legacy','none')),
    designer_id TEXT REFERENCES users(id),
    restricted_at INTEGER,
    retention_notified_at INTEGER
);

-- project_delete_confirmations (4 columns)
CREATE TABLE project_delete_confirmations (
    token_hash TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id),
    expires_at INTEGER NOT NULL
);

-- project_details (3 columns)
CREATE TABLE project_details (
    project_id TEXT PRIMARY KEY REFERENCES projects(id),
    tags TEXT NOT NULL DEFAULT '[]',
    deadline TEXT NOT NULL DEFAULT ''
);

-- project_enhancement_plans (2 columns)
CREATE TABLE project_enhancement_plans (
    project_id TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    plan_type TEXT NOT NULL CHECK(plan_type IN ('project_pass','monthly'))
);

-- project_logos (3 columns)
CREATE TABLE project_logos (
    project_id TEXT PRIMARY KEY REFERENCES projects(id),
    data BLOB NOT NULL,
    mime TEXT NOT NULL
);

-- project_members (2 columns)
CREATE TABLE project_members (
    project_id TEXT NOT NULL REFERENCES projects(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    PRIMARY KEY(project_id,user_id)
);

-- project_pins (2 columns)
CREATE TABLE project_pins (
    project_id TEXT NOT NULL REFERENCES projects(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    PRIMARY KEY(project_id,user_id)
);

-- project_team_contacts (5 columns)
CREATE TABLE project_team_contacts (
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT '',
    PRIMARY KEY(project_id,user_id)
);

-- project_testimonials (11 columns)
CREATE TABLE project_testimonials (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL,
    video TEXT NOT NULL DEFAULT '',
    approved INTEGER NOT NULL DEFAULT 0,
    data BLOB,
    mime TEXT NOT NULL DEFAULT '',
    revision INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL
);

-- projects (11 columns)
CREATE TABLE projects (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    theme TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    studio_id TEXT REFERENCES studios(id),
    visibility TEXT NOT NULL DEFAULT 'team',
    archived INTEGER NOT NULL DEFAULT 0,
    language TEXT NOT NULL DEFAULT ''
);

-- rate_limits (3 columns)
CREATE TABLE rate_limits (
    key_hash TEXT PRIMARY KEY,
    hits INTEGER NOT NULL,
    reset_at INTEGER NOT NULL
);

-- sessions (5 columns)
CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    csrf TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    studio_id TEXT REFERENCES studios(id)
);

-- share_aliases (2 columns)
CREATE TABLE share_aliases (
    token_hash TEXT PRIMARY KEY,
    share_id TEXT NOT NULL REFERENCES shares(id)
);

-- shares (7 columns)
CREATE TABLE shares (
    id TEXT PRIMARY KEY,
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    token_hash TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    revoked INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

-- slide_content (4 columns)
CREATE TABLE slide_content (
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    slide_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    PRIMARY KEY(iteration_id,slide_id)
);

-- slide_groups (5 columns)
CREATE TABLE slide_groups (
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    id TEXT NOT NULL,
    label TEXT NOT NULL,
    position INTEGER NOT NULL,
    deleted INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(iteration_id,id)
);

-- slide_image_history (5 columns)
CREATE TABLE slide_image_history (
    iteration_id TEXT NOT NULL,
    slide_id TEXT NOT NULL,
    image_version_id TEXT NOT NULL REFERENCES slide_image_versions(id) ON DELETE CASCADE,
    page_number INTEGER NOT NULL DEFAULT 0,
    image_number INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(iteration_id,slide_id,image_version_id),
    FOREIGN KEY(iteration_id,slide_id) REFERENCES presentation_slides(iteration_id,id) ON DELETE CASCADE
);

-- slide_image_versions (7 columns)
CREATE TABLE slide_image_versions (
    id TEXT PRIMARY KEY,
    parent_id TEXT REFERENCES slide_image_versions(id),
    source_version_id TEXT NOT NULL REFERENCES file_versions(id),
    mime TEXT NOT NULL,
    data BLOB NOT NULL,
    metadata TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- slide_layout (5 columns)
CREATE TABLE slide_layout (
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    slide_id TEXT NOT NULL,
    hidden INTEGER NOT NULL DEFAULT 0,
    deleted INTEGER NOT NULL DEFAULT 0,
    position INTEGER,
    PRIMARY KEY(iteration_id,slide_id)
);

-- slide_media (7 columns)
CREATE TABLE slide_media (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    mime TEXT NOT NULL,
    name TEXT NOT NULL,
    data BLOB NOT NULL,
    source_key TEXT,
    created_at TEXT NOT NULL
);

-- slide_sections (3 columns)
CREATE TABLE slide_sections (
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    slide_id TEXT NOT NULL,
    section TEXT NOT NULL,
    PRIMARY KEY(iteration_id,slide_id)
);

-- stripe_events (8 columns)
CREATE TABLE stripe_events (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    payload TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt INTEGER NOT NULL DEFAULT 0,
    error TEXT NOT NULL DEFAULT '',
    received_at INTEGER NOT NULL
);

-- studio_billing (18 columns)
CREATE TABLE studio_billing (
    studio_id TEXT PRIMARY KEY REFERENCES studios(id),
    customer_id TEXT UNIQUE,
    customer_parameters TEXT,
    subscription_id TEXT UNIQUE,
    origin_user_id TEXT REFERENCES users(id),
    onboarded_at INTEGER,
    trial_started_at INTEGER,
    trial_ends_at INTEGER,
    trial_project_used INTEGER NOT NULL DEFAULT 0,
    legacy_exempt INTEGER NOT NULL DEFAULT 0,
    plan TEXT,
    subscription_status TEXT NOT NULL DEFAULT 'none',
    paid_until INTEGER NOT NULL DEFAULT 0,
    cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
    extra_projects INTEGER NOT NULL DEFAULT 0,
    extra_seats INTEGER NOT NULL DEFAULT 0,
    subscription_json TEXT NOT NULL DEFAULT '{}',
    synced_at INTEGER NOT NULL DEFAULT 0
);

-- studio_logos (3 columns)
CREATE TABLE studio_logos (
    studio_id TEXT PRIMARY KEY REFERENCES studios(id),
    data BLOB NOT NULL,
    mime TEXT NOT NULL
);

-- studio_members (5 columns)
CREATE TABLE studio_members (
    studio_id TEXT NOT NULL REFERENCES studios(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    display_name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'member' CHECK(role IN ('admin','member')),
    PRIMARY KEY(studio_id,user_id)
);

-- studio_pack_items (7 columns)
CREATE TABLE studio_pack_items (
    id TEXT PRIMARY KEY,
    studio_id TEXT NOT NULL REFERENCES studios(id),
    kind TEXT NOT NULL CHECK(kind IN ('slide','document')),
    slide_type TEXT NOT NULL DEFAULT 'text',
    default_enabled INTEGER NOT NULL DEFAULT 1,
    position INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0
);

-- studio_pack_versions (9 columns)
CREATE TABLE studio_pack_versions (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL REFERENCES studio_pack_items(id),
    revision INTEGER NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL DEFAULT '',
    mime TEXT NOT NULL DEFAULT '',
    data BLOB,
    created_at TEXT NOT NULL,
    UNIQUE(item_id,revision)
);

-- studio_preferences (2 columns)
CREATE TABLE studio_preferences (
    user_id TEXT PRIMARY KEY REFERENCES users(id),
    theme TEXT NOT NULL DEFAULT '{}'
);

-- studios (7 columns)
CREATE TABLE studios (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    theme TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT 'en',
    business_type TEXT NOT NULL DEFAULT 'interior',
    setup_completed_at TEXT
);

-- system_slides (3 columns)
CREATE TABLE system_slides (
    iteration_id TEXT NOT NULL REFERENCES iterations(id),
    id TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('intro','changes','budget','open-questions','contacts','summary')),
    PRIMARY KEY(iteration_id,id)
);

-- users (4 columns)
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- website_ai_usage (3 columns)
CREATE TABLE website_ai_usage (
    studio_id TEXT NOT NULL REFERENCES websites(studio_id),
    month TEXT NOT NULL,
    used INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(studio_id,month)
);

-- website_assets (7 columns)
CREATE TABLE website_assets (
    id TEXT PRIMARY KEY,
    studio_id TEXT NOT NULL REFERENCES websites(studio_id),
    mime TEXT NOT NULL,
    data BLOB NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    fingerprint TEXT NOT NULL,
    UNIQUE(studio_id,fingerprint)
);

-- website_history (4 columns)
CREATE TABLE website_history (
    id TEXT PRIMARY KEY,
    studio_id TEXT NOT NULL REFERENCES websites(studio_id),
    draft TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- websites (10 columns)
CREATE TABLE websites (
    studio_id TEXT PRIMARY KEY REFERENCES studios(id),
    draft TEXT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    subscription_id TEXT UNIQUE,
    subscription_status TEXT NOT NULL DEFAULT 'none',
    paid_until INTEGER NOT NULL DEFAULT 0,
    domain TEXT NOT NULL DEFAULT '',
    domain_token TEXT NOT NULL,
    domain_verified INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL
);

-- Explicit indexes

CREATE UNIQUE INDEX billing_pending_pass ON billing_orders(project_id) WHERE kind IN ('pass','extension') AND status='pending';
CREATE UNIQUE INDEX billing_pending_prepaid_pass ON billing_orders(studio_id) WHERE kind='pass' AND project_id IS NULL AND status='pending';
CREATE UNIQUE INDEX billing_pending_subscription ON billing_orders(studio_id) WHERE kind='subscription' AND status='pending';
CREATE UNIQUE INDEX billing_pending_website ON billing_orders(studio_id) WHERE kind='website' AND status='pending';
CREATE INDEX idx_assets_project ON assets(project_id);
CREATE INDEX idx_budget_iteration ON budget_items(iteration_id);
CREATE INDEX idx_checklist_threads_root ON checklist_threads(root_id);
CREATE INDEX idx_comments_iteration ON comments(iteration_id);
CREATE INDEX idx_comments_parent ON comments(parent_id);
CREATE INDEX idx_confirmation_budget_comment ON confirmation_budget_links(comment_id);
CREATE INDEX idx_consistency_findings_iteration ON consistency_findings(iteration_id);
CREATE INDEX idx_contacts_project ON contacts(project_id);
CREATE INDEX idx_conversation_grants_email ON conversation_grants(email);
CREATE UNIQUE INDEX idx_extracted_slide ON presentation_slides(iteration_id,source_version_id,page_number,image_number) WHERE manual=0;
CREATE INDEX idx_jobs_enhancements ON jobs(project_id,type,created_at,status);
CREATE INDEX idx_jobs_status ON jobs(status,created_at);
CREATE INDEX idx_projects_user ON projects(user_id);
CREATE INDEX idx_shares_iteration ON shares(iteration_id);
CREATE INDEX idx_slides_source ON presentation_slides(iteration_id,source_version_id);
CREATE INDEX product_feedback_mail_queue ON product_feedback_outbox(status,next_attempt);
CREATE INDEX product_feedback_queue ON product_feedback(status,created_at);
CREATE INDEX product_feedback_theme ON product_feedback(theme);
CREATE INDEX project_testimonials_project ON project_testimonials(project_id);
CREATE INDEX slide_media_project ON slide_media(project_id);

-- Triggers

CREATE TRIGGER revoke_linked_conversation_grants
BEFORE DELETE ON conversation_grants BEGIN
 UPDATE conversation_grants SET revoked=1 WHERE id IN
  (SELECT grant_id FROM conversation_grant_sources WHERE source_grant_id=OLD.id);
END;

-- Migration bookkeeping for this schema version

INSERT INTO migrations (name) VALUES
    ('billing-customer-parameters-v1'),
    ('billing-v1'),
    ('checklist-v1'),
    ('consistency-questions-v1'),
    ('languages-v1'),
    ('project-clients-v1'),
    ('studio-billing-setup-v1'),
    ('studio-setup-v1'),
    ('studios-v1');

COMMIT;
